### ISSUE TITLE
RHVoice for Windows shell

### ISSUE THREAD

**Issue by Dazzo** [Olga-Yakovleva/RHVoice#1]
Hi!

I'm testing RHVoice, and it is very realistic.
But sadly I can't use it from different applications, that support Microsoft SPCHAPI engine :(
Have you planed ever make that voice as the core MS voice component?

**Comment by abitrolly** [comment]
@ratte6-1 надо в отдельную тему хотелку выносить, а то затеряется.

**Comment by paulvi** [comment]
Started #93 for stress notation

**Comment by alex19EP** [comment]
hello i know that this issue contains sum valuable feedback but it is unstructured so for now i will close it.
thanks for contribution.
