### ISSUE TITLE
RHVoice missed

### ISSUE THREAD

**Issue by bertmsk** [Olga-Yakovleva/RHVoice#10]
There's no RHVoice binary by itself.

Вообще Оля, зачем использовать такое говно как scons, когда есть Autotools?

**Comment by techtonik** [comment]
I send patches both to SCons and autotools, and between @bertmsk opinion and ESR's, I support the latter - http://esr.ibiblio.org/?p=1877


Now on topic - there is no `RHVoice-client` binary generated on Linux:
```
$ find . -iname "RHVoice-clie*"
./src/bin/rhvoice-client.c
$
```
I can't test that it works, unfortunately. I hope you don't mind that I am writing in English. It helps more people to discover answers.

**Comment by dimzon** [comment]
+1 
нетути RHVoice-client (бубунта  14.10)

**Comment by aluminiumgeek** [comment]
+1
There's no RHVoice-client nor RHVoice-test binaries after building.

**Comment by aluminiumgeek** [comment]
Ok, I investigated the problem. I see the reason of the problem is SConstruct that can't detect installed portaudio and ao libraries.
My system is Debian testing.

**Comment by dushaev** [comment]
+1 Debian 64bit - no binaries after building

**Comment by enterprise-it** [comment]
Ставил вчера RHVoice на своей VPS, с Debian, для озвучивания текстов на сайте, для слабовидящих.

Коротко установка состояла из следующих этапов:
1) В /usr/src клонируем исходники git clone https://github.com/Olga-Yakovleva/RHVoice
2) Ставим scons (тут еще потребуется установить компиляторы)
3) Далее начинаем компилировать исходники командой scons. ВАЖНО!!! В самом начале процесса компиляции идет проверка на наличие необходимых библиотек, в частности связанных с аудио подсистемой (portaudio, libao и т.д.), все их нужно будет установить. При отсутствии некоторых из них, компиляция может быть успешной, включая дальнейшую установку, но работать RHVoice не будет. У меня после компиляции и установки при отсутствии аудио пакетов, не создавались бинарники RHVoice-client и RHVoice-test в папке /usr/local/bin
4) После успешной компиляции, устанавливаем RHVoice. Для этого в папке с исходниками /usr/src/RHVoice выполняем sudo scons install и sudo ldconfig.
5) После того как RHVoice поставился, в папке /usr/local/bin, должен быть файл RHVoice-client. Вот он и выполняет озвучку.
6) Т.к. я устанавливал RHVoice на веб сервере, мне было важно чтобы озвучка выполнялась из командой строки. И здесь будет проблема, т.к. RHVoice использует dbus-launch требующий наличия X сервера. Собственно у меня dsub-launch вообще отсутствовал, поэтому пришлось установить dbus-x11. Но после этого возникла другая проблема, dsub-launch не запускался, т.к. не запускалась X подсистема. Для решения этой проблемы можно сделать .sh скрипт со следующим содержанием:
#!/bin/sh
eval `dbus-launch`
export $(dbus-launch)
cat $1 | RHVoice-client -s Elena | lame - $2

PS такой скрипт можно запускать из PHP сценария через shell_exec();

**Comment by Oire** [comment]
@enterprise-it, не брюзжания ради, а пользы дела для :smile:  
1. Вы уверены, что слабовидящим необходим самоозвучиваемый сайт? Дисклеймер: я не слабовидящий, я незрячий, то есть совсэм слепой :). Такие, как я, используют программы экранного доступа (посмотрите, например, что такое JAWS for Windows или NVDA).  
2. `shell_exec` — это же вроде оччень небезопасно, разве нет?

**Comment by enterprise-it** [comment]
Соглашусь с Вами, но конкретно, в данном случае, была такая задача, прикрутить озвучку текста, на версию сайта для слабовидящих. Точнее даже починить, после обновления ОС сервера. Сама озвучка уже была реализована, очень давно, на старой версии RHVoice.

Что касается JAWS for Windows или NVDA, то я немного знаком с этими программами. Одно время я работал над модулем для одной CMS. Задачей модуля было, создание версий сайта для слабовидящих, на основе обычной версии сайта. Вот там, как раз это делалось по уму, а именно, разметка по стандарту WAI-ARIA, максимальная поддержка работы с сайтом через клавиатуру, дополнительные панели навигации, для быстрого перехода к различным частям страницы и т.д. Короче, по задумке, полученная версия должна была максимально соответствовать WCAG 2.0 и ГОСТ Р 52872-2012. И как раз при тестировании, я использовал NVDA. На мой взгляд получалось не плохо, по крайней мере в сравнении, с тем, что NVDA выдавал на большинстве сайтов.

shell_exec - это действительно очень не безопасно. Но опять же, конкретно в данном случае, формирование аудио файла, является закрытым процессом и какие либо инъекции в него, здесь исключены. В общем использовать нужно аккуратно.

PS. Собственно вот ссылка на модуль о котором шла речь - http://test2.glaza.temp.su/?special_version=Y К сожалению на данный момент, какого либо отношения к этому проекту я не имею, т.к. покинул компанию-разработчика, на финальных этапах работ над Alpha версией проекта. Но могу сказать что проект развивается.

**Comment by dushaev** [comment]
Get solution with missed RHVoice-client. Comment these strings with '#' in SConstruct:
if conf.CheckPKG("libpulse-simple"):
if conf.CheckPKG("ao"):
if conf.CheckPKG("portaudio-2.0"):
and unindent next one string "has_giomm=conf.CheckPKG("giomm-2.4")".
Make sure that these packages installed at server: libpulse0, libao4, libportaudio2
Tested on Debian wheezy 64bit

**Comment by Master-01** [comment]
@enterprise-it, я проверил ваш скрипт, и обнаружил что после его выполнения остается в задачах dbus-daemon. То есть если я 100 раз запустил скрипт - то у меня висит 100 dbus-daemon. Подскажите пожалуйста как их не плодить? Как их убивать после выполнения?

**Comment by enterprise-it** [comment]
@Master-01 попробуйте вот так:
#!/bin/sh
eval `dbus-launch --exit-with-session`
export $(dbus-launch)
cat $1 | RHVoice-client -s Elena | lame - $2

**Comment by Crickly** [comment]
Чтобы не плодить можно:
eval dbus-launch --exit-with-session
export $(dbus-launch --exit-with-session)
 echo "Текст" | RHVoice-client -s Anna  > 'файл'
Не знаю, насколько правильно, но вроде работает

**Comment by sletix** [comment]
Что бы с dbus ничего не плодилось, нужно использовать одну сессию dbus, и следить за этим, у меня только с руби оберткой вышло.

Вот тут исполняемый файл с руби-кодом, который все сделает и вернет только путь до wav-файла:

https://gist.github.com/sletix/b4533eeff1680780c0b8

**Comment by batona** [comment]
tts.sh "Привет" ./out.wav

tts.sh:
`
#!/bin/bash
dbus_vars=/tmp/dbus_vars
if [ ! -f $dbus_vars ]; then
    echo "Файл $dbus_vars не существует\n Запускаем dbus... \n"
    #запуск dbus
    eval dbus-launch > /tmp/dbus_vars
	dbus_vars=/tmp/dbus_vars
fi

export $(cat $dbus_vars)
#wav export
echo $1 | RHVoice-client -s Anna+CLB | sox -t wav - -r 16000 -c 1 -b 16 -t wav - > $2

exit 0
`

**Comment by 4everZIP** [comment]
Пытаюсь встроить Ваше решение, но пишет:

$ ./tts.sh "Привет" ./out.wav
-bash: ./tts.sh: Permission denied

Подскажите, плз, каких ему может прав не хватать? Работаю в своей пользовательской папке. Папка, в которой скрипт и куда он по идее должен писать wav, имеет 777.

Кстати, Ваша проблема тоже может быть в правах. До этого тестировал Festival и он из под PHP тоже генерировал пустые файлы, т.к. ему прав не хватало. Но установка прав папки 777 тогда помогла.

**Comment by batona** [comment]
```
dbus_vars=/tmp/dbus_vars
if [ ! -f $dbus_vars ]; then
    echo "Файл $dbus_vars не существует\n Запускаем dbus... \n"
    #запуск dbus
    eval dbus-launch > $dbus_vars
fi

```
вот это и должно запускать сессию dbus.
Отдельно в терминале dbus-launch ошибок не дает?
Вывод должен быть типа такого:

```
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-VwmzrJEukl,guid=fc87acd9daa9cf3825ac854659eb941b
DBUS_SESSION_BUS_PID=4268
DBUS_SESSION_BUS_WINDOWID=44040193

```

**Comment by batona** [comment]
по правам я так и не разобрался. Видимо прав нет не на RHVoice-client, а на компонентоы, которые он вызывает. хз как посмотреть. На это указывает еще и то, что файл создается, но пустой. И скорее всего это не просто юникс права, а что-то более высокоуровневое типа selinux итп. Не разбирался, просто от обычного пользователя нагенерил файлы, там у меня стандартные сообщения, которые повторяются, и кинул их в папку сервера. То есть от обычного пользователя генерятся, а от www-data - нет.
