### ISSUE TITLE
Не собирается под linux

### ISSUE THREAD

**Issue by bravo321** [Olga-Yakovleva/RHVoice#100]
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking for pkg-config... (cached) yes
Checking for libpulse-simple... (cached) yes
Checking for ao... (cached) yes
Checking for portaudio-2.0... (cached) yes
Checking Speech Dispatcher version ... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/linux/audio/libao.os -c -std=c++03 -O2 -pthread -fPIC -DRHVOICE=1 -DPACKAGE=\"RHVoice\" -DVERSION=\"0.7.2\" -DWITH_LIBAO=1 -DWITH_PULSE=1 -D_REENTRANT -DWITH_PORTAUDIO=1 -Ibuild/linux/include -Isrc/include -Ibuild/linux/audio -Isrc/audio -Isrc/include -Isrc/third-party/utf8 -Isrc/third-party/tclap -Isrc/third-party/sonic -Isrc/third-party/rapidxml -Isrc/third-party/mage -Isrc/third-party/hts_engine src/audio/libao.cpp
src/audio/libao.cpp: In member function 'virtual void RHVoice::audio::{anonymous}::libao_playback_stream_impl::open(int)':
src/audio/libao.cpp:111:71: error: too many initializers for 'ao_sample_format'
       ao_sample_format sample_format={16,sample_rate,1,AO_FMT_NATIVE,0};
                                                                       ^
scons: *** [build/linux/audio/libao.os] Error 1
scons: building terminated because of errors.

Ну и да, вроде много :

> This structure describes the format of audio samples. 
> 
> typedef struct {
>   int bits; /* bits per sample */
>   int rate; /* samples per second (in a single channel) */
>   int channels; /* number of audio channels */
>   int byte_format; /* Byte ordering in sample, see constants below */
> } ao_sample_format;
> Relevant Struct Members
> byte_format
> Specifies the ordering of the sample bytes. The value of this member is ignored when samples have only 8 bits. Use the following constants:
> AO_FMT_LITTLE - Samples are in little-endian order.
> AO_FMT_BIG - Samples are in big-endian order.
> AO_FMT_NATIVE - Samples are in the native ordering of the computer.

**Comment by bravo321** [comment]
Как оказалось, с версией libao4 v 1.2.2 и соответственно libao-dev v 1.2.2 собирается нормально.
А у меня стояла v 1.1.0, так что сам дурак :)

**Comment by abitrolly** [comment]
Стоит добавить проверку на версии?

**Comment by bravo321** [comment]
Ну как бы в ubuntu 16.04 , стандартно , ставится именно 1.1.0 ... А в 18.04, уже 1.2.2 , можно бы просто в документации указать с какими либами собирать нужно ..

**Comment by Olga-Yakovleva** [comment]
Пока не понятная ситуация. Я проверила сборку на Ubuntu 16.04 с libao 
1.1.0 - и у меня проблема не воспроизводится.

**Comment by abitrolly** [comment]
Если добавить Travis CI в серисы репозитория, то я тогда пришлю pull request с конфигурацией Travis для сборки на Ubuntu 16.04

**Comment by abitrolly** [comment]
В 1.1.0 тоже 5 инициализаторов - https://git.xiph.org/?p=libao.git;a=blob;f=include/ao/ao.h;h=cb8c0356fdc4d7afee340437acb13991ef3885dc;hb=ed28ea3ccee6bddc5584190578e77d8ed9379193#l79
```
typedef struct ao_sample_format {
         int  bits; /* bits per sample */
         int  rate; /* samples per second (in a single channel) */
         int  channels; /* number of audio channels */
         int  byte_format; /* Byte ordering in sample, see constants below */
         char *matrix; /* input channel location/ordering */
} ao_sample_format;
```

**Comment by bravo321** [comment]
Ну возможно у меня , из-за бардака в системе какие-то не те либы цеплялись, но мне помогло удаление libao из системы sudo apt purge libao* и после этого установка версии 1.2.2 из deb пакетов
libao4_1.2.2+20180113-1ubuntu1_amd64.deb
libao-dev_1.2.2+20180113-1ubuntu1_amd64.deb
а стояли : 
`
Libao у меня :
Package: libao-dev
Version: 1.1.0-3ubuntu1
---
Package: libao4
Version: 1.1.0-3ubuntu1
`

**Comment by abitrolly** [comment]
Если проблемы больше нет, то можешь закрывать. Для успокоения можешь в контейнере собрать на чистой 16.04
