### ISSUE TITLE
Можно хоть как-то добавить паузу между предложениями ? 

### ISSUE THREAD

**Issue by frenzymind** [Olga-Yakovleva/RHVoice#101]
Здравствуйте. Есть ли способ добавлять/регулировать паузу между предложениями/словами ? Хотя бы костыльный.
В багтреке такие вопросы есть, но ответа нет.

**Comment by zvezdochiot** [comment]
Вам наверное сюда: https://github.com/Olga-Yakovleva/RHVoice/issues/97

**Comment by zvezdochiot** [comment]
@frenzymind say> Есть ли способ добавлять/регулировать паузу между предложениями/словами ? Хотя бы костыльный.

Если для воспроизведения пользется консоль, то можно "подрихтовать" https://github.com/BASH-Auto-Tools/rhvoicebookreader

**Comment by alex19EP** [comment]
Duplicate of #97
