### ISSUE TITLE
languages/Georgian/* aren't installed any more

### ISSUE THREAD

**Issue by yurivict** [Olga-Yakovleva/RHVoice#109]
I tried to update the FreeBSD port but these files aren't installed any more, while the README talks about Georgian language as something that is supported.

**Comment by Olga-Yakovleva** [comment]
The license of the voice is problematic. Please see the corresponding section [here](https://github.com/Olga-Yakovleva/RHVoice/wiki/License). Packagers have to decide for themselves. Georgian can be enabled at build-time..
