### ISSUE TITLE
не собирается в linux-mint

### ISSUE THREAD

**Issue by linerfx** [Olga-Yakovleva/RHVoice#119]
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... no
Checking for portaudio-2.0... no
Checking Speech Dispatcher version ... no
ImportError: No module named lxml:
Не понятно, что такое 'ao'. В инструкции по установке говорите, что нужно иметь версии PulsAudio не только для воспроизведения, но и для разработки. Сервер PulsAudio работает, на их сайте ничего не сказано о версии для разработки. Значит ли это, что нужно собирать у себя их клонированный дистрибутив?

**Comment by beqabeqa473** [comment]
здравствуйте.

установите lxml через pip например

pip install lxml

On 11/2/19, linerfx <notifications@github.com> wrote:
> scons: Reading SConscript files ...
> Mkdir("build/linux")
> Checking whether the C compiler works... yes
> Checking whether the C++ compiler works... yes
> Checking for pkg-config... yes
> Checking for libpulse-simple... yes
> Checking for ao... no
> Checking for portaudio-2.0... no
> Checking Speech Dispatcher version ... no
> ImportError: No module named lxml:
> Не понятно, что такое 'ao'. В инструкции по установке говорите, что нужно
> иметь версии PulsAudio не только для воспроизведения, но и для разработки.
> Сервер PulsAudio работает, на их сайте ничего не сказано о версии для
> разработки. Значит ли это, что нужно собирать у себя их клонированный
> дистрибутив?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/119


-- 
with best regards beqa

**Comment by linerfx** [comment]
Благодарю за ответ!
Если кому интересно, сначала нужно установить pip (это оказывается процессор XML и HTML для python'а):
`sudo apt install python-pip`
потом отсутствующий модуль
`sudo pip install lxml`
а после уже по инструкции

**Comment by zvezdochiot** [comment]
@linerfx say:
>Если кому интересно

Никому не интересно. Закрывай к шутам этот issue. :(

**Comment by zstanecic** [comment]
Ольге надо обновить инструкцию сборки.

**Comment by linerfx** [comment]
> @linerfx say:
> 
> > Если кому интересно
> 
> Никому не интересно. Закрывай к шутам этот issue. :(
Поня́л... Не знал что нужно/уполномочен закрывать ветку. Закрываю, если кнопка ниже "Close and comment" для этого. Однако, тебя не "звездочьот" зовут, а "никому". Зашыфровался, крипт?
Вопрос напоследок:
Есть ли какой общий interface (с/с++) в программе, библиотека может, чтобы брать ф-ции для графической оболочки на подобии "Балаболки" для wind'ы? Я-б взялся. В linux'е не хватает такого счастья.
Или можно было'б документ опубликовать с описанием (экспортируемых) ф-ций, которые брать с этой целью. Или может список файлов, которые смотреть для этого.
Тем не менее, время будет, почитаю программку. Хорошая, спасибо за труд!

**Comment by linerfx** [comment]
> @linerfx say:
> 
> > Если кому интересно
> 
> Никому не интересно. Закрывай к шутам этот issue. :(



Поня́л... Не знал что нужно/уполномочен закрывать ветку. Закрываю, если кнопка ниже "Close and comment" для этого. Однако, тебя не "звездочьот" зовут, а "никому". Зашыфровался, крипт?
Вопрос напоследок:
Есть ли какой общий interface (с/с++) в программе, библиотека может, чтобы брать ф-ции для графической оболочки на подобии "Балаболки" для wind'ы? Я-б взялся. В linux'е не хватает такого счастья.
Или можно было'б документ опубликовать с описанием (экспортируемых) ф-ций, которые брать с этой целью. Или может список файлов, которые смотреть для этого.
Тем не менее, время будет, почитаю программку. Хорошая, спасибо за труд!

**Comment by beqabeqa473** [comment]
Смотрите RHVoice.h заголовочный файл для интерфейса c-api

On 11/3/19, linerfx <notifications@github.com> wrote:
>> @linerfx say:
>>
>> > Если кому интересно
>>
>> Никому не интересно. Закрывай к шутам этот issue. :(
> Поня́л... Не знал что нужно/уполномочен закрывать ветку. Закрываю, если
> кнопка ниже "Close and comment" для этого. Однако, тебя не "звездочьот"
> зовут, а "никому". Зашыфровался, крипт?
> Вопрос напоследок:
> Есть ли какой общий interface (с/с++) в программе, библиотека может, чтобы
> брать ф-ции для графической оболочки на подобии "Балаболки" для wind'ы? Я-б
> взялся. В linux'е не хватает такого счастья.
> Или можно было'б документ опубликовать с описанием (экспортируемых) ф-ций,
> которые брать с этой целью. Или может список файлов, которые смотреть для
> этого.
> Тем не менее, время будет, почитаю программку. Хорошая, спасибо за труд!
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/119#issuecomment-549109166


-- 
with best regards beqa

**Comment by linerfx** [comment]
ОК, его как раз сейчас и смотрю, вникаю...

**Comment by zvezdochiot** [comment]
@linerfx say:
>Есть ли какой общий interface (с/с++) в программе,

Смотри как компилируется модуль для speech-dispatcher: sd_rhvoice.

**Comment by abitrolly** [comment]
> Ольге надо обновить инструкцию сборки.

А где, кстати, инструкция, чтобы обновить? Тоже столкнулся с тем, что `lxml` нужен.

**Comment by alex19EP** [comment]
> 
> 
> > Ольге надо обновить инструкцию сборки.
> 
> А где, кстати, инструкция, чтобы обновить? Тоже столкнулся с тем, что `lxml` нужен.

инструкция: doc/en/Compiling-on-Linux.md но про lxml туда пока писать не надо. я гляну в чём тут дело.

**Comment by zstanecic** [comment]
LXML тут нужен и под Windows. 

Без него пакеты не соберёшь.

**Comment by abitrolly** [comment]
> > > Ольге надо обновить инструкцию сборки.
> > 
> > 
> > А где, кстати, инструкция, чтобы обновить? Тоже столкнулся с тем, что `lxml` нужен.
> 
> инструкция: doc/en/Compiling-on-Linux.md но про lxml туда пока писать не надо. я гляну в чём тут дело.

Есть два коммита откуда `lxml` взялся.
https://github.com/Olga-Yakovleva/RHVoice/commit/34dbda511d3a8a0a67556bf805a35af8204e07c9
https://github.com/Olga-Yakovleva/RHVoice/commit/c684650d57072d1be3eaae6e305246e8808c4821

К сожалению, во втором случае не очень понятно, зачем. Возможно для дебага надо тоже было вывести в читабельном виде. Но есть альтернативы https://stackoverflow.com/questions/749796/pretty-printing-xml-in-python/1206856#1206856

**Comment by alex19EP** [comment]
> LXML тут нужен и под Windows.

он нужен только под windows.

> c684650

хм. интересно почему он импортируется и на linux. надо глянуть.

**Comment by alex19EP** [comment]
> хм. интересно почему он импортируется и на linux. надо глянуть.

не могу повторить в своей среде. может кто-то попробовать собрать под linux без lxml?

**Comment by abitrolly** [comment]
@alex19EP не повторяется проблема с `lxml` на Fedora 33 и на Ubuntu. https://ci.appveyor.com/project/yakshaveinc/rhvoice/build/job/lsola7ysb0xda9pg

Я тоже не нашёл пути по которому он бы триггерился.
