### ISSUE TITLE
string "***" crashes RHVoice engine

### ISSUE THREAD

**Issue by mrchen077** [Olga-Yakovleva/RHVoice#121]
Android - multiple versions
RHVoice: ver 1.0.1
Voice: any

When the text contains a string '***', the RHVoice engine stops and an error message is displayed:
'Text-to-speech engine is not working properly'.

This is a serious problem because *** is often used as a chapter separator.

For comparison - Google TTS does not display this behaviour, it handles *** seemlessly.

**Comment by Olga-Yakovleva** [comment]
Thank you for reporting this. Now that I'm testing, it seems RHVoice has 
a problem with sequences of symbols in general on all the platforms.

**Comment by alex19EP** [comment]
hello @mrchen077 can't reproduce on latest version from play-market. it seems @Olga-Yakovleva fixed it.
will close the issue. if the problem is something else, please reopen.
