### ISSUE TITLE
Get rid of auto_ptr

### ISSUE THREAD

**Issue by KOLANICH** [Olga-Yakovleva/RHVoice#124]
They are deprecated in favour of new types.

**Comment by zvezdochiot** [comment]
https://github.com/Olga-Yakovleva/RHVoice/graphs/contributors . @KOLANICH , you are not visible on the list.

**Comment by KOLANICH** [comment]
If I had been, you wouln't have left this comment.

**Comment by zvezdochiot** [comment]
If you were on the list, your words would have meaning.

**Comment by al-mission-2016** [comment]
It's time to move the project to **C++11** or above. There is **`std::unique_ptr`** in **C++11** out of the box that is a safer replacement for deprecated **`std::auto_ptr`**.
Alternatively, we can use **`boost::scoped_ptr`**, but this is an unnecessary dependency for the project.

[`auto_ptr` vs `unique_ptr`](https://stackoverflow.com/questions/3451099/stdauto-ptr-to-stdunique-ptr)
[why is `autp_ptr` deprecated in C++11](https://www.quora.com/Why-is-auto_ptr-deprecated-in-C++11)
