### ISSUE TITLE
4 kHz parasite

### ISSUE THREAD

**Issue by KOLANICH** [Olga-Yakovleva/RHVoice#133]
![rhvoice](https://user-images.githubusercontent.com/240344/76875309-4dd65100-6868-11ea-8056-400487f2da6f.png)

[natalia.zip](https://github.com/Olga-Yakovleva/RHVoice/files/4344463/a.zip)

RHVoice has been built with Mage support.

**Comment by KOLANICH** [comment]
@zvezdochiot, do you hear the same 4 kHz tone in your setup?

**Comment by KOLANICH** [comment]
Strange, I don't hear this tone on the sound emitted by `speech-dispatcher`. Needs moar analysis on what is happening.

**Comment by zvezdochiot** [comment]
How do you filter this frequency? How do you conduct an ABX-test?

**Comment by KOLANICH** [comment]
>How do you filter this frequency? How do you conduct an ABX-test?

Haven't done any ABX tests. Just found RHVoice-test output strange and tested multiple voices and found all them strange the same way - 4khz tone is hearable when speaking. Have created a file,opened it in Audacity, selected spectrogram, saw 4 Khz tone on it, selected the part where it is present, played it and confirmed that it is that is strange.

If you look at the spectrograms of the same phrase spoken by different voices you can see that 4khz is present in the same parts of the sentence, though in different amount.

**Comment by zvezdochiot** [comment]
I have a problem gently filtering out this frequency. And after that, the ABX test will show everything.

**Comment by KOLANICH** [comment]
It was a macrodef in libmage related to RHVoice-specific customizations. I have forgotten to set it.

Here is the differrence between right and wrong output (colors except black are not very meaningful, since RGB model was used): ![natalia_difference](https://user-images.githubusercontent.com/240344/77554080-818b2980-6ead-11ea-80db-ace57113ff8e.png)
