### ISSUE TITLE
Не собирается в Windows 10 Home 64bit

### ISSUE THREAD

**Issue by vldmr-d** [Olga-Yakovleva/RHVoice#134]
Не собирается, потому что нет совместимости с Windows XP. 
Как можно решить эту не совместимость?

**scons -h
scons: Reading SConscript files ...
Mkdir("build\windows")
Checking for WiX toolset(cached) yes
Checking for NSIS(cached) yes
Mkdir("build\windows\x86")
Configuring the build system for x86
Checking for Visual C++ ... (cached) yes
Visual C++ version is 14.2
Checking for Windows XP compatibility ... (cached) no
Error: Windows XP compatibility cannot be enabled**

**Comment by beqabeqa473** [comment]
попробуйте установить значение переменной enable_xp_compat на False

On 3/18/20, volodymyr <notifications@github.com> wrote:
> Не собирается, потому что нет совместимости с Windows XP.
> Как можно решить эту не совместимость?
>
> **scons -h
> scons: Reading SConscript files ...
> Mkdir("build\windows")
> Checking for WiX toolset(cached) yes
> Checking for NSIS(cached) yes
> Mkdir("build\windows\x86")
> Configuring the build system for x86
> Checking for Visual C++ ... (cached) yes
> Visual C++ version is 14.2
> Checking for Windows XP compatibility ... (cached) no
> Error: Windows XP compatibility cannot be enabled**
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/134


-- 
with best regards beqa

**Comment by zvezdochiot** [comment]
@vldmr-d say:
>Как

Не хочет `scons`, пробуй `cmake`: https://github.com/KOLANICH/RHVoice/tree/cmake .

**Comment by beqabeqa473** [comment]
перед тем как отвечать я бы советовал разобраться в вопросе.

зачем навязывать еще какой-то сборщик, если можно просто передать
scons-у одион параметр для отключения поддержки windows xp.

On 3/18/20, звездочёт <notifications@github.com> wrote:
> @vldmr-d say:

>>Как

>

> Не хочет `scons`, пробуй `cmake`:
> https://github.com/KOLANICH/RHVoice/tree/cmake .

>

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/Olga-Yakovleva/RHVoice/issues/134#issuecomment-600627212


-- 
with best regards beqa

**Comment by vldmr-d** [comment]
Спасибо большое, поменял эту строчку на False в SConstruct и все собралось!
---------------------------------------------------------------------------
vars.Add(BoolVariable("enable_xp_compat","Target Windows XP",True))
на эту
vars.Add(BoolVariable("enable_xp_compat","Target Windows XP",False))
---------------------------------------------------------------------------
Еще бы научится запускать так легко как в Linux, на Линуксе эта программа мне говорит
время и погоду каждый час, очень удобно.

**Comment by zvezdochiot** [comment]
@beqabeqa473 say:
>перед тем как отвечать я бы советовал разобраться в вопросе. 

Так вопрос не в сборке? Я то сам пользую `scons`, но данный `issue` не единственный в своём роде. И `cmake` версия некоторых выручает. Лишней точно не будет.

**Comment by vldmr-d** [comment]
> 
> попробуйте установить значение переменной enable_xp_compat на False
> […](#)
> On 3/18/20, volodymyr ***@***.***> wrote: Не собирается, потому что нет совместимости с Windows XP. Как можно решить эту не совместимость? **scons -h scons: Reading SConscript files ... Mkdir("build\windows") Checking for WiX toolset(cached) yes Checking for NSIS(cached) yes Mkdir("build\windows\x86") Configuring the build system for x86 Checking for Visual C++ ... (cached) yes Visual C++ version is 14.2 Checking for Windows XP compatibility ... (cached) no Error: Windows XP compatibility cannot be enabled** -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #134
> -- with best regards beqa

Спасибо большое, поменял эту строчку на False в SConstruct и все собралось!
**vars.Add(BoolVariable("enable_xp_compat","Target Windows XP",True))**
на эту
**vars.Add(BoolVariable("enable_xp_compat","Target Windows XP",False))**
Может кому пригодится
Еще бы научится запускать так легко как в Linux, на Линуксе эта программа мне говорит
время и погоду каждый час, очень удобно.

**Comment by beqabeqa473** [comment]
так надо думать где это советовать. нельзя же куда угодно ляпать?

зачем человеку советовать вещь, которая может и не работать на винде,
если достаточно передать один единственный параметр в scons.


On 3/18/20, звездочёт <notifications@github.com> wrote:
> @beqabeqa473 say:
>>перед тем как отвечать я бы советовал разобраться в вопросе.
>
> Так вопрос не в сборке? Я то сам пользую `scons`, но данный `issue` не
> единственный в своём роде. И `cmake` версия некоторых выручает. Лишней точно
> не будет.
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/134#issuecomment-600632901


-- 
with best regards beqa

**Comment by zvezdochiot** [comment]
@beqabeqa473 say:
>так надо думать где это советовать

Вижу, что каждый останется при своём мнении.
