### ISSUE TITLE
Post Android app to Huawei Application Gallery?

### ISSUE THREAD

**Issue by gregko** [Olga-Yakovleva/RHVoice#136]
Sorry for posting here, don't know how to contact the author (Olga) directly. Newer Huawei devices don't have Google Play store anymore, Huawei App Gallery (HAG) is the default app store on them. There are no TTS engines or voices available at HAG at all, and they don't come with any TTS pre-installed (maybe the very latest Huawei flagship models have Huawei TTS pre installed, not sure, but not 2019 and older models). RHVoice would be very needed there.

I have a read aloud app that needs TTS voices, that Huawei wants me to post there, but the proposition is a non-starter without q TTS engine. If necessary, I could help with submitting RHVoice app there, or it's fairly simple to create your own Huawei developer account and submit an app.

I must also add that I'm impressed with the improved quality of RHVoice voices, particularly in Russian, compared to my testing of RHVoice several months ago. Great job!

Greg Kochaniak, Hyperionics

**Comment by alex19EP** [comment]
hello @gregko can you provide Huawei  developer docs. and i will look into it. 
thanks.

**Comment by gregko** [comment]
With Olga's email permission I already submitted RHVoice to Huawei app store some time ago.

**Comment by alex19EP** [comment]
ok nice if you post the link i will close the issue.

**Comment by gregko** [comment]
Hi Alex,
unlike for Google Play, I don't know how to display app pages in Huawei App Gallery (HAG) outside of their phones and HAG app. All I can tell is that version 1.2.1 is listed there, the exact Android build downloaded from Olga's Wiki page (package name com.github.olga_yakovleva.rhvoice.android). HAG Analytics says that the package had 123 new downloads in the last 7 days. If you want, I'll gladly transfer the ownership of this product in HAG to you or someone else, after Olga's approval.

Honestly, I don't know what's the future of HAG. When I submitted my own product there about 2 months ago, initially the experience was good, they approved the app quickly and approved updates within 1 day of submission. Now my latest update of the same app is stuck in "Review" status for over 3 weeks, and no word from them what's wrong, why they don't approve the update, clicking the "Review reminder" button as no effect. If things won't improve there, I'll probably give up on HAG.

Greg

**Comment by alex19EP** [comment]
hello Greg. I do not think that it is necessary to transfer ownership. thank.
I needed a link to add to the documentation, but if it’s complicated, we’ll just forget about it. 😉
🎆Thank you for your work. I will close this issue.
cheers

**Comment by gregko** [comment]
Yes, such link may not be possible at all, I really don't know. Instead, you could write in the docs: 

On any Huawei phone or tablet, start AppGallery, then type RHVoice into the search box and press the Search button.

I tried to attach 2 screenshot from my phone. They show "Open" button instead of "Install", because RHVoice is already installed on this device.

![Screenshot_20200616_181524_com huawei appmarket](https://user-images.githubusercontent.com/1746812/84834022-7b18d380-affe-11ea-95e7-3eaae560868a.jpg)
![Screenshot_20200616_181554_com huawei appmarket](https://user-images.githubusercontent.com/1746812/84834023-7b18d380-affe-11ea-8ffd-88451f7ff2c6.jpg)


Greg

**Comment by zhimbura** [comment]
Hello, could you please tell me if the app is still published in AppGallery? I can't find it in the search.

**Comment by zstanecic** [comment]
@gregko you were in charge of this...

**Comment by zhimbura** [comment]
Can we add auto-publishing for Rustore? It's practically the official store in Russia.

**Comment by gregko** [comment]
In Huawei app gallery? No, I removed it, there was little interest in this product. You could download APK file to install it from 3rd party sites, if you don’t have Google Play on your home, for example from apkpure.com

**Comment by zhimbura** [comment]
> I don't know how data the rustore wants to have for it to be published.

- apk
- icon
- description 
- short description
- screenshots 
- short explain to about WRITE_EXTERNAL_STORAGE

Here is a list of what is needed for publication, and of course, you need to create an account. I could handle the publication and have already prepared a draft of the rules for moderation, but I was asked to confirm that I am not a fraud and that I am the author. If the author does not mind, could you please send me a screenshot from the Play Market, which RuStore support requires for passing moderation? After that, I would be able to publish versions simply by downloading the APK from F-Droid.

**Comment by zstanecic** [comment]
cc
@Olga-Yakovleva 
@louderpages 
Your thoughts?

**Comment by Olga-Yakovleva** [comment]
Hi everyone,


I have no objections against the app being built from source code  and 
published in another Android app store. But it must be published as a 
build of an open-source project, not connected to the app on Google 
Play.   In your communications with the store please explain that you 
are publishing an app built from sources licensed under GPL. GPL gives 
you the right to buiild and distribute the binaries. Plese also link to 
rhvoice.org in your app description.
