### ISSUE TITLE
Перестал собираться Centos 7.7

### ISSUE THREAD

**Issue by krooto** [Olga-Yakovleva/RHVoice#137]
Перестал собираться ( 
CentOS Linux release 7.7.1908 (Core)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39) 

Cloning into 'RHVoice'...
remote: Enumerating objects: 851, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (381/381), done.
remote: Total 12090 (delta 461), reused 680 (delta 380), pack-reused 11239
Receiving objects: 100% (12090/12090), 398.68 MiB | 26.99 MiB/s, done.
Resolving deltas: 100% (7127/7127), done.
Checking out files: 100% (1486/1486), done.
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... yes
Checking whether the C++ compiler works... yes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... yes
Checking for portaudio-2.0... yes
Checking Speech Dispatcher version ... no

Пропущено ...

In file included from src/core/pitch.cpp:20:0:
src/include/core/pitch.hpp: In instantiation of 'void std::vector<_Tp, _Alloc>::_M_insert_aux(std::vector<_Tp, _Alloc>::iterator, const _Tp&) [with _Tp = RHVoice::pitch::stylizer::point_t; _Alloc = std::allocator<RHVoice::pitch::stylizer::point_t>; std::vector<_Tp, _Alloc>::iterator = __gnu_cxx::__normal_iterator<RHVoice::pitch::stylizer::point_t*, std::vector<RHVoice::pitch::stylizer::point_t> >; typename std::_Vector_base<_Tp, _Alloc>::pointer = RHVoice::pitch::stylizer::point_t*]':
/usr/include/c++/4.8.2/bits/stl_vector.h:913:28:   required from 'void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = RHVoice::pitch::stylizer::point_t; _Alloc = std::allocator<RHVoice::pitch::stylizer::point_t>; std::vector<_Tp, _Alloc>::value_type = RHVoice::pitch::stylizer::point_t]'
src/include/core/pitch.hpp:57:42:   required from 'RHVoice::pitch::stylizer::result_t RHVoice::pitch::stylizer::stylize(const iter_t&, const iter_t&) const [with iter_t = __gnu_cxx::__normal_iterator<double*, std::vector<double> >; RHVoice::pitch::stylizer::result_t = std::vector<double>]'
src/core/pitch.cpp:278:118:   required from here
src/include/core/pitch.hpp:76:12: error: non-static const member 'const size_t RHVoice::pitch::stylizer::point_t::index', can't use default assignment operator
     struct point_t
            ^
src/include/core/pitch.hpp:76:12: error: non-static const member 'const double RHVoice::pitch::stylizer::point_t::value', can't use default assignment operator
In file included from /usr/include/c++/4.8.2/vector:69:0,
                 from src/include/core/hts_labeller.hpp:20,
                 from src/include/core/hts_label.hpp:24,
                 from src/include/core/hts_input.hpp:20,
                 from src/core/pitch.cpp:19:
/usr/include/c++/4.8.2/bits/vector.tcc:335:16: note: synthesized method 'RHVoice::pitch::stylizer::point_t& RHVoice::pitch::stylizer::point_t::operator=(const RHVoice::pitch::stylizer::point_t&)' first required here 
    *__position = __x_copy;
                ^
scons: *** [build/linux/core/pitch.os] Error 1
scons: building terminated because of errors.
"scons" command filed with exit code 2.

**Comment by zvezdochiot** [comment]
Это git или какая то из https://github.com/Olga-Yakovleva/RHVoice/releases ?

**Comment by krooto** [comment]
clone из master

**Comment by krooto** [comment]
Решил проблему: 
https://github.com/Olga-Yakovleva/RHVoice/issues/79#issue-345858974
Видимо изменилось что-то )
