### ISSUE TITLE
prefer_primary_language не работает

### ISSUE THREAD

**Issue by AlexeyCAT** [Olga-Yakovleva/RHVoice#139]
Указываю в конфиге prefer_primary_language=false. Всё равно rhvoice читает например строку "google.com" следующим образом: "google точка com". RHVoice установлен как аддон к nvda 2020.1. В nvda стоит галочка "использовать язык синтезатора для чтения знаков и символов пунктуации".

**Comment by kvark128** [comment]
Этот флаг не работает, потому что NVDA передаёт на синтезатор само слово «точка», а не фактический символ точки. Как вариант, сделайте профиль с основным английским голосом (например Alan+Aleksandr). Правда в этом случае вся пунктуация будет английской.

**Comment by AlexeyCAT** [comment]
kvark128, спасибо за предложение, но всё-таки хочу, чтобы в английском тексте пунктуация читалась на английском, а в русском тексте читалась на русском.

После вашего ответа я в окне "Произношение символов (Русский)" для символа "." и для символа ". в конце предложения" установил параметр "Передавать фактический символ на синтезатор" = всегда. Потом то же самое проделал для окна "Произношение символов (Английский)".

Но это не помогло, не знаете почему?

**Comment by kvark128** [comment]
Сам RHVoice по умолчанию вообще никакую пунктуацию не читает. За это отвечает параметр punctuation_mode.
Установите его в значение some, а в список punctuation_list добавьте символ точки. После этого синтезатор начнёт читать фактическую точку получаемую от NVDA, но подозреваю, что такое постоянное чтение точек вас очень скоро утомит.
Пожалуй это единственный способ настроить чтение пунктуации в соответствии с языком окружающего текста.

**Comment by AlexeyCAT** [comment]
Спасибо! Для моей цели такое решение подходит.
