### ISSUE TITLE
No language resources are available

### ISSUE THREAD

**Issue by techtonik** [Olga-Yakovleva/RHVoice#14]
I am trying to understand how RHVoice works to wrap it into Python module on Linux. I've managed to build `RHVoice-test`, but did not install anything. I copied and renamed libraries it complained about, but now it complains about missing language resources:

```
$ echo test|./build/linux/test/RHVoice-test
No language resources are available
```

What are those? Where I can read about them? Where to download them, and how to make RHVoice-test see them?

**Comment by techtonik** [comment]
Looks like it is just files in `data/languages` dir in source root. So on Windows I can just place `data` dit near to RHVoice.dll, but on Linux I don't know. How to specify the path to this data dir? Still need more info what are those files.

**Comment by gBopHuk** [comment]
Поддерживаю данного товарища. Собрал по инструкции из wiki c такими параметрами

<pre>
scons "CXXFLAGS=-g -std=c++11"
sudo scons install "prefix=/usr" "libdir=/usr/lib64" "sysconfdir=/etc"
sudo ldconfig
</pre>

Затем получаю ошибку :  
<pre>
$ echo test |RHVoice-test        
No language resources are available
</pre>

Расположение файлов такое: 
<pre>
/etc/RHVoice
/etc/RHVoice/RHVoice.conf
/etc/tts.d/rhvoice-en.voiceman
/etc/tts.d/rhvoice.voiceman
/usr/bin/RHVoice-client
/usr/bin/RHVoice-make-hts-labels
/usr/bin/RHVoice-service
/usr/bin/RHVoice-test
/usr/bin/RHVoice-transcribe-sentences
/usr/bin/sd_rhvoice
/usr/lib64/libRHVoice.so.2
/usr/lib64/libRHVoice.so.2.0.0
/usr/lib64/libRHVoice_audio.so.0
/usr/lib64/libRHVoice_audio.so.0.0.0
/usr/lib64/libRHVoice_core.so.0
/usr/lib64/libRHVoice_core.so.0.0.0
/usr/share/RHVoice
/usr/share/RHVoice/languages
/usr/share/RHVoice/languages/English
/usr/share/RHVoice/languages/English/accents.dt
/usr/share/RHVoice/languages/English/cmulex.fst
/usr/share/RHVoice/languages/English/cmulex.lts
/usr/share/RHVoice/languages/English/downcase.fst
/usr/share/RHVoice/languages/English/gpos.fst
/usr/share/RHVoice/languages/English/key.fst
/usr/share/RHVoice/languages/English/labelling.xml
/usr/share/RHVoice/languages/English/language.info
/usr/share/RHVoice/languages/English/lseq.fst
/usr/share/RHVoice/languages/English/msg.fst
/usr/share/RHVoice/languages/English/numbers.fst
/usr/share/RHVoice/languages/English/phonemes.xml
/usr/share/RHVoice/languages/English/phrasing.dt
/usr/share/RHVoice/languages/English/spell.fst
/usr/share/RHVoice/languages/English/syl.fst
/usr/share/RHVoice/languages/English/tok.fst
/usr/share/RHVoice/languages/English/tones.dt
/usr/share/RHVoice/languages/Esperanto
/usr/share/RHVoice/languages/Esperanto/downcase.fst
/usr/share/RHVoice/languages/Esperanto/g2p.fst
/usr/share/RHVoice/languages/Esperanto/gpos.fst
/usr/share/RHVoice/languages/Esperanto/key.fst
/usr/share/RHVoice/languages/Esperanto/labelling.xml
/usr/share/RHVoice/languages/Esperanto/language.info
/usr/share/RHVoice/languages/Esperanto/msg.fst
/usr/share/RHVoice/languages/Esperanto/numbers.fst
/usr/share/RHVoice/languages/Esperanto/phonemes.xml
/usr/share/RHVoice/languages/Esperanto/phrasing.dt
/usr/share/RHVoice/languages/Esperanto/spell.fst
/usr/share/RHVoice/languages/Esperanto/syl.fst
/usr/share/RHVoice/languages/Esperanto/tok.fst
/usr/share/RHVoice/languages/Esperanto/untranslit.fst
/usr/share/RHVoice/languages/Georgian
/usr/share/RHVoice/languages/Georgian/downcase.fst
/usr/share/RHVoice/languages/Georgian/g2p.fst
/usr/share/RHVoice/languages/Georgian/gpos.fst
/usr/share/RHVoice/languages/Georgian/key.fst
/usr/share/RHVoice/languages/Georgian/labelling.xml
/usr/share/RHVoice/languages/Georgian/language.info
/usr/share/RHVoice/languages/Georgian/msg.fst
/usr/share/RHVoice/languages/Georgian/numbers.fst
/usr/share/RHVoice/languages/Georgian/phonemes.xml
/usr/share/RHVoice/languages/Georgian/phrasing.dt
/usr/share/RHVoice/languages/Georgian/spell.fst
/usr/share/RHVoice/languages/Georgian/syl.fst
/usr/share/RHVoice/languages/Georgian/tok.fst
/usr/share/RHVoice/languages/Russian
/usr/share/RHVoice/languages/Russian/clitics.fst
/usr/share/RHVoice/languages/Russian/dict.fst
/usr/share/RHVoice/languages/Russian/downcase.fst
/usr/share/RHVoice/languages/Russian/english_phone_mapping.fst
/usr/share/RHVoice/languages/Russian/g2p.fst
/usr/share/RHVoice/languages/Russian/gpos.fst
/usr/share/RHVoice/languages/Russian/key.fst
/usr/share/RHVoice/languages/Russian/labelling.xml
/usr/share/RHVoice/languages/Russian/language.info
/usr/share/RHVoice/languages/Russian/lseq.fst
/usr/share/RHVoice/languages/Russian/msg.fst
/usr/share/RHVoice/languages/Russian/numbers.fst
/usr/share/RHVoice/languages/Russian/phonemes.xml
/usr/share/RHVoice/languages/Russian/phrasing.dt
/usr/share/RHVoice/languages/Russian/rulex_dict.fst
/usr/share/RHVoice/languages/Russian/rulex_rules.fst
/usr/share/RHVoice/languages/Russian/spell.fst
/usr/share/RHVoice/languages/Russian/split.fst
/usr/share/RHVoice/languages/Russian/stress.fsm
/usr/share/RHVoice/languages/Russian/stress.fst
/usr/share/RHVoice/languages/Russian/syl.fst
/usr/share/RHVoice/languages/Russian/tok.fst
/usr/share/RHVoice/languages/Russian/untranslit.fst
/usr/share/RHVoice/voices
/usr/share/RHVoice/voices/alan
/usr/share/RHVoice/voices/alan/dur.pdf
/usr/share/RHVoice/voices/alan/lf0.pdf
/usr/share/RHVoice/voices/alan/lf0.win1
/usr/share/RHVoice/voices/alan/lf0.win2
/usr/share/RHVoice/voices/alan/lf0.win3
/usr/share/RHVoice/voices/alan/lpf.pdf
/usr/share/RHVoice/voices/alan/lpf.win1
/usr/share/RHVoice/voices/alan/mgc.pdf
/usr/share/RHVoice/voices/alan/mgc.win1
/usr/share/RHVoice/voices/alan/mgc.win2
/usr/share/RHVoice/voices/alan/mgc.win3
/usr/share/RHVoice/voices/alan/tree-dur.inf
/usr/share/RHVoice/voices/alan/tree-lf0.inf
/usr/share/RHVoice/voices/alan/tree-lpf.inf
/usr/share/RHVoice/voices/alan/tree-mgc.inf
/usr/share/RHVoice/voices/alan/voice.info
/usr/share/RHVoice/voices/alan/voice.params
/usr/share/RHVoice/voices/aleksandr
/usr/share/RHVoice/voices/aleksandr/dur.pdf
/usr/share/RHVoice/voices/aleksandr/lf0.pdf
/usr/share/RHVoice/voices/aleksandr/lf0.win1
/usr/share/RHVoice/voices/aleksandr/lf0.win2
/usr/share/RHVoice/voices/aleksandr/lf0.win3
/usr/share/RHVoice/voices/aleksandr/lpf.pdf
/usr/share/RHVoice/voices/aleksandr/lpf.win1
/usr/share/RHVoice/voices/aleksandr/mgc.pdf
/usr/share/RHVoice/voices/aleksandr/mgc.win1
/usr/share/RHVoice/voices/aleksandr/mgc.win2
/usr/share/RHVoice/voices/aleksandr/mgc.win3
/usr/share/RHVoice/voices/aleksandr/tree-dur.inf
/usr/share/RHVoice/voices/aleksandr/tree-lf0.inf
/usr/share/RHVoice/voices/aleksandr/tree-lpf.inf
/usr/share/RHVoice/voices/aleksandr/tree-mgc.inf
/usr/share/RHVoice/voices/aleksandr/voice.info
/usr/share/RHVoice/voices/aleksandr/voice.params
/usr/share/RHVoice/voices/anna
/usr/share/RHVoice/voices/anna/dur.pdf
/usr/share/RHVoice/voices/anna/lf0.pdf
/usr/share/RHVoice/voices/anna/lf0.win1
/usr/share/RHVoice/voices/anna/lf0.win2
/usr/share/RHVoice/voices/anna/lf0.win3
/usr/share/RHVoice/voices/anna/lpf.pdf
/usr/share/RHVoice/voices/anna/lpf.win1
/usr/share/RHVoice/voices/anna/mgc.pdf
/usr/share/RHVoice/voices/anna/mgc.win1
/usr/share/RHVoice/voices/anna/mgc.win2
/usr/share/RHVoice/voices/anna/mgc.win3
/usr/share/RHVoice/voices/anna/tree-dur.inf
/usr/share/RHVoice/voices/anna/tree-lf0.inf
/usr/share/RHVoice/voices/anna/tree-lpf.inf
/usr/share/RHVoice/voices/anna/tree-mgc.inf
/usr/share/RHVoice/voices/anna/voice.info
/usr/share/RHVoice/voices/anna/voice.params
/usr/share/RHVoice/voices/clb
/usr/share/RHVoice/voices/clb/dur.pdf
/usr/share/RHVoice/voices/clb/lf0.pdf
/usr/share/RHVoice/voices/clb/lf0.win1
/usr/share/RHVoice/voices/clb/lf0.win2
/usr/share/RHVoice/voices/clb/lf0.win3
/usr/share/RHVoice/voices/clb/lpf.pdf
/usr/share/RHVoice/voices/clb/lpf.win1
/usr/share/RHVoice/voices/clb/mgc.pdf
/usr/share/RHVoice/voices/clb/mgc.win1
/usr/share/RHVoice/voices/clb/mgc.win2
/usr/share/RHVoice/voices/clb/mgc.win3
/usr/share/RHVoice/voices/clb/tree-dur.inf
/usr/share/RHVoice/voices/clb/tree-lf0.inf
/usr/share/RHVoice/voices/clb/tree-lpf.inf
/usr/share/RHVoice/voices/clb/tree-mgc.inf
/usr/share/RHVoice/voices/clb/voice.info
/usr/share/RHVoice/voices/clb/voice.params
/usr/share/RHVoice/voices/elena
/usr/share/RHVoice/voices/elena/dur.pdf
/usr/share/RHVoice/voices/elena/lf0.pdf
/usr/share/RHVoice/voices/elena/lf0.win1
/usr/share/RHVoice/voices/elena/lf0.win2
/usr/share/RHVoice/voices/elena/lf0.win3
/usr/share/RHVoice/voices/elena/lpf.pdf
/usr/share/RHVoice/voices/elena/lpf.win1
/usr/share/RHVoice/voices/elena/mgc.pdf
/usr/share/RHVoice/voices/elena/mgc.win1
/usr/share/RHVoice/voices/elena/mgc.win2
/usr/share/RHVoice/voices/elena/mgc.win3
/usr/share/RHVoice/voices/elena/tree-dur.inf
/usr/share/RHVoice/voices/elena/tree-lf0.inf
/usr/share/RHVoice/voices/elena/tree-lpf.inf
/usr/share/RHVoice/voices/elena/tree-mgc.inf
/usr/share/RHVoice/voices/elena/voice.info
/usr/share/RHVoice/voices/elena/voice.params
/usr/share/RHVoice/voices/irina
/usr/share/RHVoice/voices/irina/dur.pdf
/usr/share/RHVoice/voices/irina/lf0.pdf
/usr/share/RHVoice/voices/irina/lf0.win1
/usr/share/RHVoice/voices/irina/lf0.win2
/usr/share/RHVoice/voices/irina/lf0.win3
/usr/share/RHVoice/voices/irina/lpf.pdf
/usr/share/RHVoice/voices/irina/lpf.win1
/usr/share/RHVoice/voices/irina/mgc.pdf
/usr/share/RHVoice/voices/irina/mgc.win1
/usr/share/RHVoice/voices/irina/mgc.win2
/usr/share/RHVoice/voices/irina/mgc.win3
/usr/share/RHVoice/voices/irina/tree-dur.inf
/usr/share/RHVoice/voices/irina/tree-lf0.inf
/usr/share/RHVoice/voices/irina/tree-lpf.inf
/usr/share/RHVoice/voices/irina/tree-mgc.inf
/usr/share/RHVoice/voices/irina/voice.info
/usr/share/RHVoice/voices/irina/voice.params
/usr/share/RHVoice/voices/natia
/usr/share/RHVoice/voices/natia/dur.pdf
/usr/share/RHVoice/voices/natia/lf0.pdf
/usr/share/RHVoice/voices/natia/lf0.win1
/usr/share/RHVoice/voices/natia/lf0.win2
/usr/share/RHVoice/voices/natia/lf0.win3
/usr/share/RHVoice/voices/natia/lpf.pdf
/usr/share/RHVoice/voices/natia/lpf.win1
/usr/share/RHVoice/voices/natia/mgc.pdf
/usr/share/RHVoice/voices/natia/mgc.win1
/usr/share/RHVoice/voices/natia/mgc.win2
/usr/share/RHVoice/voices/natia/mgc.win3
/usr/share/RHVoice/voices/natia/tree-dur.inf
/usr/share/RHVoice/voices/natia/tree-lf0.inf
/usr/share/RHVoice/voices/natia/tree-lpf.inf
/usr/share/RHVoice/voices/natia/tree-mgc.inf
/usr/share/RHVoice/voices/natia/voice.info
/usr/share/RHVoice/voices/natia/voice.params
/usr/share/RHVoice/voices/slt
/usr/share/RHVoice/voices/slt/dur.pdf
/usr/share/RHVoice/voices/slt/lf0.pdf
/usr/share/RHVoice/voices/slt/lf0.win1
/usr/share/RHVoice/voices/slt/lf0.win2
/usr/share/RHVoice/voices/slt/lf0.win3
/usr/share/RHVoice/voices/slt/lpf.pdf
/usr/share/RHVoice/voices/slt/lpf.win1
/usr/share/RHVoice/voices/slt/mgc.pdf
/usr/share/RHVoice/voices/slt/mgc.win1
/usr/share/RHVoice/voices/slt/mgc.win2
/usr/share/RHVoice/voices/slt/mgc.win3
/usr/share/RHVoice/voices/slt/tree-dur.inf
/usr/share/RHVoice/voices/slt/tree-lf0.inf
/usr/share/RHVoice/voices/slt/tree-lpf.inf
/usr/share/RHVoice/voices/slt/tree-mgc.inf
/usr/share/RHVoice/voices/slt/voice.info
/usr/share/RHVoice/voices/slt/voice.params
/usr/share/RHVoice/voices/spomenka
/usr/share/RHVoice/voices/spomenka/dur.pdf
/usr/share/RHVoice/voices/spomenka/lf0.pdf
/usr/share/RHVoice/voices/spomenka/lf0.win1
/usr/share/RHVoice/voices/spomenka/lf0.win2
/usr/share/RHVoice/voices/spomenka/lf0.win3
/usr/share/RHVoice/voices/spomenka/lpf.pdf
/usr/share/RHVoice/voices/spomenka/lpf.win1
/usr/share/RHVoice/voices/spomenka/mgc.pdf
/usr/share/RHVoice/voices/spomenka/mgc.win1
/usr/share/RHVoice/voices/spomenka/mgc.win2
/usr/share/RHVoice/voices/spomenka/mgc.win3
/usr/share/RHVoice/voices/spomenka/tree-dur.inf
/usr/share/RHVoice/voices/spomenka/tree-lf0.inf
/usr/share/RHVoice/voices/spomenka/tree-lpf.inf
/usr/share/RHVoice/voices/spomenka/tree-mgc.inf
/usr/share/RHVoice/voices/spomenka/voice.info
/usr/share/RHVoice/voices/spomenka/voice.params
/usr/share/dbus-1/services/com.github.OlgaYakovleva.RHVoice.service
/usr/share/doc/RHVoice-0.5
/usr/share/doc/RHVoice-0.5/COPYING
/usr/share/doc/RHVoice-0.5/NEWS
/usr/share/doc/RHVoice-0.5/README
</pre>

Расскажите пожалуйста что где должно лежать?

**Comment by gBopHuk** [comment]
Нашёл в файле SConstruct параметр DESTDIR. Решение оказалось таким
scons install "DESTDIR=/usr"

I found solution in SConstruct file. This is a DESTDIR arg of "scons install" 
scons install "DESTDIR=/usr"
