### ISSUE TITLE
Внешние проигрыватели?

### ISSUE THREAD

**Issue by zvezdochiot** [Olga-Yakovleva/RHVoice#140]
Привет @Olga-Yakovleva .

:question: Не знаю с какой версии это пошло, знаю что в `0.7.1` "труба" вида https://github.com/Olga-Yakovleva/RHVoice/issues/110#issuecomment-533900712 работала, и можно было пользовать внешние проигрыватели (aplay, play или даже ffplay). В `1.2.2` "труба" уже не работает (создаётся файл `-`). Мож стоит починить?

**Comment by nshmyrev** [comment]
/dev/stdout вместо -

**Comment by zvezdochiot** [comment]
Привет, @nshmyrev .

Хм. Однако работает:

```sh
$ echo "привет" | RHVoice-test -p elsena -o /dev/stdout 2>/dev/null | aplay /dev/stdin 2>/dev/null
```

**Comment by zvezdochiot** [comment]
:warning: Нет! Ошибся! Всё равно не работает! Наверное это как то связано с отсутствием линковки к `libasound2`.

**Comment by alex19EP** [comment]
hello @zvezdochiot do you reali need to use rhvoice-test? because this component got disabled for a reason. 

can you use platform native api? for example speetch-despatcher.

**Comment by zvezdochiot** [comment]
Hi @alex19EP .

:question: Yes, I can use `speetch-despatcher`. But how do I use external players in `spd-say`?

**Comment by alex19EP** [comment]
> 
> 
> Hi @alex19EP .
> 
> ❓ Yes, I can use `speetch-despatcher`. But how do I use external players in `spd-say`?

oh sorry At first I did not understand your situation completely. Unfortunately, this is not possible at the moment. ticket in upstream. brailcom/speechd/issues/348

**Comment by KOLANICH** [comment]
@zvezdochiot , shouldn't lihao deal with alsa itself?

**Comment by zvezdochiot** [comment]
Hi @KOLANICH .

The current `scons` assembly produces the same result as your `cmake` assembly. The `-` file is created, instead of being launched into `stdout`. But even a direct indication of `/dev/stdout` and `/dev/stdin` yields nothing.
```sh
$ objdump -x libRHVoice_audio.so.1.1.0 | grep -w NEEDED | awk '{print $2}'
libRHVoice_core.so.3
libao.so.4
libpulse-simple.so.0
libpulse.so.0
libportaudio.so.2
libasound.so.2
libpthread.so.0
libstdc++.so.6
libm.so.6
libgcc_s.so.1
libc.so.6
```

**Comment by Olga-Yakovleva** [comment]
Sorry, didn't realize that the word fix in my commit message would
close this automatically. Please test and reopen if there are still problems.

**Comment by zvezdochiot** [comment]
Привет @Olga-Yakovleva .

Проблема решена. "Труба" снова работает. :+1:
