### ISSUE TITLE
breaks SAPI on WIN 10 when unisntalling

### ISSUE THREAD

**Issue by yuukiw** [Olga-Yakovleva/RHVoice#141]
Everytime i uninstall the voices the SAPI on Windows 10 breaks.

IS this a known issue or any idea how to prevent it?

**Comment by alex19EP** [comment]
hello @yuukiw i tried to reproduce but didn’t succeed. you can recheck. and provide detailed repro-steps.
thanks.

**Comment by yuukiw** [comment]
Cant reproduce it either on the newest windows version.

So it could have beem a MS issue that only appeared when you changed something in relation with the tts voice/engine.
