### ISSUE TITLE
Random interruptions of synthesis in the middle of the phrase with the RHVoice-test (PortAudio backend)

### ISSUE THREAD

**Issue by dmikushin** [Olga-Yakovleva/RHVoice#157]
I've been testing RHVoice-test with PortAudio backend on MacOS Catalina and noticed random interruptions in synthesis playback. It tracks down to a silent emergency stop in the context of voice playback.

**Comment by alex19EP** [comment]
i think #138 looks related.

**Comment by dmikushin** [comment]
The following PR resolves the issue: https://github.com/Olga-Yakovleva/RHVoice/pull/156 Apparently, the playback buffer flushes in the end of each sentence. And if the sentence remainder does not fill the entire buffer (is shorter), the underflow status is returned by PortAudio.

@alex19EP please consider this issue & fix as of high importance.

**Comment by dmikushin** [comment]
> i think #138 looks related.

Right, I think these are the same interruptions!
