### ISSUE TITLE
missed libRHVoice_audio.so.0

### ISSUE THREAD

**Issue by sisteamnik** [Olga-Yakovleva/RHVoice#16]
Ubuntu 14.04

RHVoice-test: error while loading shared libraries: libRHVoice_audio.so.0: cannot open shared object file: No such file or directory

**Comment by sisteamnik** [comment]
Problem solved `sudo ldconfig` command

**Comment by techtonik** [comment]
And what is `sudo ldconfig` and why it is needed?
