### ISSUE TITLE
Некорректная работа RHVoice на Raspberry Pi Zero

### ISSUE THREAD

**Issue by Dasercom** [Olga-Yakovleva/RHVoice#166]
Суть проблемы проста.
На Raspberry Pi Zero спокойно можно установить любую TTS. Первым делом я проверял всё на обычном linux и всё работало. Но после установки на Pi я столкнулся с проблемами. 
Первым делом я грешил на то, что я использую USB звуковую карту, но после настройки, проблемы не ушли.
Я воспользовался одним советом с QA Stack.

> Если вам не нужен встроенный аудиочип (например, аналоговый выход или аудио HDMI), отключите его, и тогда аудиоустройство USB может стать основным устройством:
> 
> Отключить встроенный звук.
> Откройте /etc/modprobe.d/raspi-blacklist.confи добавьте blacklist snd_bcm2835.
> Позвольте аудиоустройству USB быть устройством по умолчанию.
> Откройте /lib/modprobe.d/aliases.confи закомментируйте строкуoptions snd-usb-audio index=-2
> перезагрузка
> sudo reboot
> Проверьте это.
> $ aplay /usr/share/sounds/alsa/Front_Center.wav

Вообщем звук на звуковой карте появился. Но при проверке на RHvoice, данная команда не заставляет мигать даже индикатор на звуковой карте. 
`echo «Привет я синтезатор речи» | RHVoice-test -p anna`

Но другие TTS на подобии Festival. Спокойно выводят звук, даже через звуковую карту. И заставляют мигать индикатор.

Подозрения падают на код, ведь даже звуковая карта не подает признаков работы на Raspberry Pi Zero W,

Прошу помогите, подскажите что сделать.

**Comment by Aculeasis** [comment]
Если aplay работает, то - `echo "Привет я синтезатор речи" | RHVoice-test -p anna -o - | aplay -q -`

**Comment by Dasercom** [comment]
> Если aplay работает, то - `echo "Привет я синтезатор речи" | RHVoice-test -p anna -o - | aplay -q -`

Спасибо большое, парился несколько дней, думал что всё время ошибался с звуковой картой. Но всё работает, благодарю.
