### ISSUE TITLE
Stress mark support / Поддержка знаков ударения

### ISSUE THREAD

**Issue by aleksejrs** [Olga-Yakovleva/RHVoice#17]
См. статью «[знак ударения](https://ru.wikipedia.org/wiki/%D0%97%D0%BD%D0%B0%D0%BA_%D1%83%D0%B4%D0%B0%D1%80%D0%B5%D0%BD%D0%B8%D1%8F)» в Википедии.  Было бы удобно указывать прямо в тексте, например для исправления при использовании [AwesomeTTS для Anki](https://ankiatts.appspot.com/).

**Comment by aleksejrs** [comment]
Код символа в Юникоде — U+0301, он ставится после соответствующей буквы. В Windows XP и более ранних в шрифте Verdana он отображается не на той букве, поэтому символ в некоторых текстах может стоять перед ударной буквой.

В текстах в дореформенной орфографии и словарях (по статье в Википедии) иногда также используется обратное ударение (наклонено в другую сторону). В словарях оно означает побочное ударение. Код «грависа» в Юникоде — U+0300 (на 1 меньше обычного ударения).

**Comment by alex19EP** [comment]
Duplicate of #93

**Comment by aleksejrs** [comment]
Why? This one is older.

**Comment by alex19EP** [comment]
> 
> 
> Why? This one is older.

ok will reconsider.

**Comment by Olga-Yakovleva** [comment]
Does anyone know if Ukrainian texts use the same character to indicate stress?

**Comment by alex19EP** [comment]
> 
> 
> Does anyone know if Ukrainian texts use the same character to indicate stress?

FYI @velmyshanovnyi

**Comment by velmyshanovnyi** [comment]
в УКР текстах, по стандарту используется U+0301, но как и написано выше, может быть использован и U+0300 или другие аналогично выглядевшие символы. Юзеры часто путаит из, или по незнанию али по привычке.

так что могут быть использованы не только левый/правый, но и прямой
` или ' и иногда даже прямые кавычки "

и не стоит сбрасывась со счетов так же апострофы, для которых юзерами могут быть испрользованы эти и другие (похожие) значки...

**Comment by velmyshanovnyi** [comment]
мясо
м'ясо
м`ясо
м"ясо
мЯсо


все варианты могут быть использованы в тексте, в зависимости от того, кто именно и где пишет текст.

(на телефонах юзер не парится, и может юзать тот знак, который ему проще поставить, на его клавиатуре, а иногда и просто его проигнорировать, как в первом слове)

**Comment by Olga-Yakovleva** [comment]
I forgot to comment here earlier, but the implementation for Russian is
now in the master branch and needs testing.

**Comment by zstanecic** [comment]
Здравствуйте, Ольга!

Как попробовать этот функционал, что нужно включить, как пользоваться?

**Comment by Olga-Yakovleva** [comment]
It is always enabled in the latest version. If a vowel letter in a 
Russian text is followed by an acute accent character (U+0301), it will 
be stressed.

**Comment by Olga-Yakovleva** [comment]
Implemented the same thing for Ukrainian. I need somebody to test this: both that it is working and, probably more importantly, that I haven't broken anything by this change by mistake.

**Comment by zstanecic** [comment]
Hi Olga,

I’ve tested this for Russian, and it works only if the word is in the RHVoice dictionary and or user dictionary.

If there is no word, it ignores the sign and reduces wovels.

**Comment by zstanecic** [comment]
P.s. i am going to test this with the new changes

**Comment by Olga-Yakovleva** [comment]
> I’ve tested this for Russian, and it works only if the word is in the 
> RHVoice dictionary and or user dictionary.
> 
> If there is no word, it ignores the sign and reduces wovels.

Please give me a couple words as examples, so it would be easier for me 
to find the reason for this bug. It isn't easy to think of a 
out-of-dictionary word right away.

**Comment by zstanecic** [comment]
Ольга, можете попробовать словоформу местоимения 

Чего

Это местоимение не находится в словаре RHVOICE.

**Comment by Olga-Yakovleva** [comment]
Are you sure that the calling program doesn't process the text itself? 
For example, NVDA seems to insert spaces between some types of 
characters, which breaks all the native rules of the tts. So the testing 
must be done with something we know doesn't do any special processing of 
its own, such as the RHVoice-test utility.

**Comment by zstanecic** [comment]
Yep, NVDA can insert spaces, but where?

I am running RHVoice on windows, and I don’t know do we have RHVoice test for windows available?

Maybe I can test with it.

NVDA threats the stress mark as the combining diacritic mark.

**Comment by Olga-Yakovleva** [comment]
Do you know how to open the speech properties dialog for SAPI5 voices? 
It can be used to test such things. I will try to test myself on a 
virtual machine a bit later.

**Comment by zstanecic** [comment]
Yep, i know. I will do it later, too, because I am using RHVoice with NVDA addon

**Comment by zstanecic** [comment]
I have tested the function from the sapi5 properties, and it works properly, even with the words which are not parts of the dictionary. 

So, the conclusion is that NVDA does something when processing the text.

I am going to research a bit.

**Comment by zstanecic** [comment]
I’ve found an error. 

The problem with NVDA is that NVDA doesn’t pass the symbol to the synthesizer.

I’ve needed to turn this on in NVDA settings.

Conclusion, I will need to contribute a patch to the symbols file.

The feature can be considered stable, if all works also at your side.

**Comment by Olga-Yakovleva** [comment]
I also received a private confirmation about the Ukrainian language,
so closing as implemented.
