### ISSUE TITLE
Compilation with SCons is broken

### ISSUE THREAD

**Issue by Olga-Yakovleva** [Olga-Yakovleva/RHVoice#170]
I should have tested before merging pr #135. I am aware of the problems and will deal with them.

**Comment by Olga-Yakovleva** [comment]
I think my two commits fix the problems.

**Comment by beqabeqa473** [comment]
cannot confirm it on windows

**Comment by beqabeqa473** [comment]
cannot build on windows.

Configuring  C:\Users\user\rhvoice\src\core/config.h.in into C:\Users\user\rhvoice\src\core\c
onfig.h ...

scons: warning: Two different environments were specified for target C:\Users\user\rhvoice\src
\core\config.h,
        but they appear to have the same action: _action(target, source, env)
File "C:\Users\user\rhvoice\src\core\SConscript", line 54, in processConfig

scons: *** Multiple ways to build the same target were specified for: C:\Users\user\rhvoice\sr
c\core\config.h  (from ['const char CONFIG_PATH[] = "config";', 'const char DATA_PATH[] = "data
";'] and from ['const char CONFIG_PATH[] = "config";', 'const char DATA_PATH[] = "data";'])
File "C:\Users\user\rhvoice\src\core\SConscript", line 54, in processConfig
