### ISSUE TITLE
RHVoice-data?

### ISSUE THREAD

**Issue by zvezdochiot** [Olga-Yakovleva/RHVoice#172]
Привет @Olga-Yakovleva .

Вопрос уже подымался в других issues, но отдельно не звучал.

Перенесите голоса в отдельный репозиторий, пожалуйста. Сейчас пошли слияния с @KOLANICH и проверять работоспособность `cmake` и `scons` стало совсем неудобно. Были бы голоса отдельно, всё стало бы гораздо проще.

**Comment by alex19EP** [comment]
hello @zvezdochiot i think this is similar to #125

**Comment by zvezdochiot** [comment]
Oh! I already forgot about him.

**Comment by zvezdochiot** [comment]
Hi @alex19EP .

I can't close. Can you do it?

**Comment by alex19EP** [comment]
hello @zvezdochiot i think this is similar to #125 
Duplicate of #125

**Comment by KOLANICH** [comment]
What's inconvenent with the CMake scripts by me?

**Comment by zvezdochiot** [comment]
Hi @KOLANICH .

Not in `cmake` it's inconvenient, but keeping everything in one basket (both the engine and the voices) is inconvenient for cloning.

**Comment by KOLANICH** [comment]
Yeah, trully.

BTW, you can just pull, or fetch and reset --hard, so you don't have to download GiBs every time.
