### ISSUE TITLE
Compilation issues on windows

### ISSUE THREAD

**Issue by beqabeqa473** [Olga-Yakovleva/RHVoice#179]
hello all.

several issues were observed while compiling rhvoice on windows.

1. building with scons is still broken.
Configuring C:\Users\user\rhvoice\src\core/config.h.in into C:\Users\user\rhvoice\src\core\c
onfig.h ...
scons: warning: Two different environments were specified for target C:\Users\user\rhvoice\src
\core\config.h,
but they appear to have the same action: _action(target, source, env)
File "C:\Users\user\rhvoice\src\core\SConscript", line 54, in processConfig
scons: *** Multiple ways to build the same target were specified for: C:\Users\user\rhvoice\sr
c\core\config.h (from ['const char CONFIG_PATH[] = "config";', 'const char DATA_PATH[] = "data
";'] and from ['const char CONFIG_PATH[] = "config";', 'const char DATA_PATH[] = "data";'])
File "C:\Users\user\rhvoice\src\core\SConscript", line 54, in processConfig

2. after replacing smartPTR to sharedPTR, building sapi5 part was broken while using vs2019
including memory in com.cpp and com.hpp seems to fix a problem.

thanks.

**Comment by Olga-Yakovleva** [comment]
I'm working on the fix.

**Comment by Olga-Yakovleva** [comment]
Please test.

**Comment by maniyax** [comment]
@Olga-Yakovleva, check your e-mail, please!

**Comment by maniyax** [comment]
@Olga-Yakovleva, check your e-mail, please!

**Comment by beqabeqa473** [comment]
confirmed as fixed
