### ISSUE TITLE
there is no rhvoice folder in the %appdata% directory

### ISSUE THREAD

**Issue by fatihyuksek1** [Olga-Yakovleva/RHVoice#188]
I couldn't find a rhvoice folder in the %appdata% directory. The config file was there according to the wiki article but there is no such folder called rhvoice in the %appdata% directory. I was going to change the config file to create a new voice profile but I couldn't. I am using windows 10 64-bit and SAPI 5

**Comment by zstanecic** [comment]
Hi,

For now, you need to create it manually, and yes, it’s a bug.

**Comment by fatihyuksek1** [comment]
So  can you send me An example file so I can do this easier or give some instructions?

iPhone’umdan gönderildi

**Comment by Olga-Yakovleva** [comment]
The directory is now being created on first use. And the simplified 
configuration file with the links is copied there. So to those who can 
build and test please do. If there is no file, it should appear, but if 
there is, it should remain as is, no replacement.

**Comment by zstanecic** [comment]
I will test this now.

Best,

Zvonimir

**Comment by zstanecic** [comment]
Тхе иссуе ис фиџед.

Ит њоркс.

**Comment by alex19EP** [comment]
@zstanecic your last comment looks strange. please, edit it.

**Comment by zstanecic** [comment]
I’ve posted it via e mail, I am not able to edit it.

I said that this function works.

**Comment by alex19EP** [comment]
> I’ve posted it via e mail.

for the future, I recommend using the github web interface.

closing as fixed in efac9bf
