### ISSUE TITLE
Проблема с установкой пакета Arch Linux rhvoice-git

### ISSUE THREAD

**Issue by seniorivn** [Olga-Yakovleva/RHVoice#19]
В aur есть пакет rhvoice-git он требует следующие зависимости:
- expat
- pcre
- sox
- libunistring
- python2
- portaudio
- glibmm
- scons
- gcc
- flite-full>=1.4 (building from AUR)

все зависимости кроме flite-full присутствуют в системе.
flite-full отсутствует в aur, но присутствует flite, который выдает ошибку при компиляции.
в wiki инструкции в этом репозитории сказано: 

> Для компиляции RHVoice в вашей системе должны быть установлены следующие программы:
> GCC
> Pkg-config
> SCons

при компиляции без установленного пакета flite выдается ошибка компиляции:

> ==> Starting build...
> scons: Reading SConscript files ...
> Mkdir("build/linux")
> Checking whether the C compiler works... yes
> Checking whether the C++ compiler works... yes
> Checking for pkg-config... yes
> Checking for libpulse-simple... yes
> Checking for ao... yes
> Checking for portaudio-2.0... yes
> Checking for giomm-2.4... yes
> ImportError: No module named nvda:
>   File "/tmp/yaourt-tmp-ivn/aur-rhvoice-git/src/RHVoice/SConstruct", line 305:
>     build_for_linux(base_env)
>   File "/tmp/yaourt-tmp-ivn/aur-rhvoice-git/src/RHVoice/SConstruct", line 261:
>     duplicate=0)
>   File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
>     return method(_args, *_kw)
>   File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
>     return _SConscript(self.fs, _files, *_subst_kw)
>   File "/usr/lib/python2.7/site-packages/SCons/Script/SConscript.py", line 260:
>     exec _file_ in call_stack[-1].globals
>   File "/tmp/yaourt-tmp-ivn/aur-rhvoice-git/src/RHVoice/data/SConscript", line 5:
>     import packaging.nvda
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ==> ERROR: Makepkg was unable to build rhvoice-git.

and pkgbuild is:

``` bash
pkgname=rhvoice-git
pkgver=20141006
pkgrel=1
pkgdesc="free and open source speech synthesizer for Russian language"
arch=('i686' 'x86_64')
url="https://github.com/Olga-Yakovleva/RHVoice"
license=('GPL3')
depends=('expat' 'pcre' 'sox' 'libunistring' 'python2' 'portaudio' 'glibmm')
makedepends=('scons' 'gcc')
optdepends=('alsa-utils: for using aplay')
provides=('rhvoice')
replaces=('rhvoice')
backup=('etc/RHVoice/RHVoice.conf')

_gitroot='https://github.com/Olga-Yakovleva/RHVoice.git'
_gitname='RHVoice'

build() {
    cd "$srcdir"
    msg "Connecting to GIT server...."

    if [[ -d "$_gitname" ]]; then
        cd "$_gitname" && git pull origin
        msg "The local files are updated."
    else
        git clone "$_gitroot" "$_gitname"
    fi

    msg "GIT checkout done or server timeout"
    msg "Starting build..."
    cd "$srcdir/$_gitname"

    scons prefix="/usr" sysconfdir="/etc" || return 1

}

package() {
  echo "Installing package"
  cd "$srcdir/$_gitname"
  mkdir -p ${pkgdir}{/usr/bin/,/etc/RHVoice,/usr/lib/,/usr/include,/usr/share/RHVoice}
  install -D build/linux/service/RHVoice{-service,-client} "${pkgdir}/usr/bin/"
  install -D build/linux/test/RHVoice-test "${pkgdir}/usr/bin/"
  install -D build/linux/sd_module/sd_rhvoice "${pkgdir}/usr/bin/"
  install -D -m 644 config/RHVoice.conf "${pkgdir}/etc/RHVoice/"
  cp -R config/dicts/ "$pkgdir/etc/RHVoice/"
  install -m 644 build/linux/lib/libRHVoice.so "${pkgdir}/usr/lib"
  install -m 644 build/linux/core/libRHVoice_core.so "${pkgdir}/usr/lib"
  install -m 644 build/linux/audio/libRHVoice_audio.so "${pkgdir}/usr/lib"
  install -m 644 src/include/RHVoice.h "${pkgdir}/usr/include/"
  cp -R data/*  "${pkgdir}/usr/share/RHVoice"
  rm "${pkgdir}/usr/share/RHVoice/SConscript"
}
```

**Comment by vantu5z** [comment]
Попробуй этот 
https://github.com/ArchAssault-Project/archassault/blob/master/packages/flite-full/PKGBUILD

**Comment by seniorivn** [comment]
@vantu5z, та же ошибка компиляции(исходники взял в другом месте, но версия по и хэш архива те же)
```
patching file config/common_make_rules
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for a BSD-compatible install... /usr/bin/install -c
checking for ar... ar
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for mmap... yes
checking sys/soundcard.h usability... yes
checking sys/soundcard.h presence... yes
checking for sys/soundcard.h... yes
checking machine/soundcard.h usability... no
checking machine/soundcard.h presence... no
checking for machine/soundcard.h... no
checking sys/audioio.h usability... no
checking sys/audioio.h presence... no
checking for sys/audioio.h... no
checking mmsystem.h usability... no
checking mmsystem.h presence... no
checking for mmsystem.h... no
configure: creating ./config.status
config.status: creating config/config
config.status: creating config/system.mak
making in ...
making in include ...
making in src ...
making in src/audio ...
ar: `u' modifier ignored since `D' is the default (see `U')
ar: ../../..//tmp/yaourt-tmp-ivn/aur-flite/lib/libflite.shared.a: No such file or directory
../../config/common_make_rules:116: recipe for target '/tmp/yaourt-tmp-ivn/aur-flite/obj/src/audio/.build_so' failed
make[2]: *** [/tmp/yaourt-tmp-ivn/aur-flite/obj/src/audio/.build_so] Error 1
../config/common_make_rules:132: recipe for target '/tmp/yaourt-tmp-ivn/aur-flite/obj/src/.make_build_dirs' failed
make[1]: *** [/tmp/yaourt-tmp-ivn/aur-flite/obj/src/.make_build_dirs] Error 2
config/common_make_rules:132: recipe for target '/tmp/yaourt-tmp-ivn/aur-flite/obj//.make_build_dirs' failed
make: *** [/tmp/yaourt-tmp-ivn/aur-flite/obj//.make_build_dirs] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build flite-full.
==> Restart building flite ? [y/N]
==> ------------------------------

**Comment by vantu5z** [comment]
@seniorivn , cтранно, используя вышеуказанный PKGBUILD и патч (лежит рядом с ним) у меня пакет flite-full собрался без ошибок.

**Comment by seniorivn** [comment]
@vantu5z мда, вроде всё правильно делал, на выходных разберусь, спасибо.

**Comment by vantu5z** [comment]
@seniorivn , ради эксперимента попробовал установить rhvoice с flite вместо flite-full. 
1. Установил flite 2.0.0-2 из AUR, встал без ошибок.
2. Подправил PKGBUILD rhvoice-git из AUR, заменив зависимость flite-full>=1.4 на flite>=2.0.
3. rhvoice-git собрался без ошибок и работает.

У Вас получилось установить его?

**Comment by seniorivn** [comment]
@vantu5z кажется у меня даже сам flite не собирался, я не стал разбираться, приспособил festival, потом может быть вернусь к этом вопросу, проблема явно не массовая, возможно даже моя локальная.

**Comment by alex19EP** [comment]
old. not actual any more
