### ISSUE TITLE
Using MaryTTS voices in RHVoice

### ISSUE THREAD

**Issue by elnursamedzade** [Olga-Yakovleva/RHVoice#190]
Hello there.
Is it possible to use a unit selection voice built with MaryTTS with RHVoice on android?
What changes need to be made to the source code?
Please enlighten me. Thank you.!

**Comment by Olga-Yakovleva** [comment]
No, it is not possible. And I'm not going to work on it myself. Unit 
selection is a related, but separate technology, which seems much more 
difficult to get right.

And even if voices from two different tts systems are built on the same 
technology, it isn't possible to just use them outside of their native 
tts without new special code in that other tts, which I'm also not 
planing to implement.
