### ISSUE TITLE
reminder: add new russian voice to android

### ISSUE THREAD

**Issue by zstanecic** [Olga-Yakovleva/RHVoice#195]
Hi to all,
this issue is just a reminder.
can you add the new russian voice to android and allow compiling the 3rd party voice data?
best,
Zvonimir

**Comment by zstanecic** [comment]
@Olga-Yakovleva 
Does the latest change allow compiling 3rd party voice data, not in the checksums?

**Comment by Olga-Yakovleva** [comment]
These are two separate issues: I've implemented the short-term
request, but the long-term question of supporting third-party voices
on Android will be solved later, not in this release, as I can't take
even more time now. Please open a separate issue for it.

**Comment by zstanecic** [comment]
Ok

**Comment by Olga-Yakovleva** [comment]
This change is now on Google Play, so closing.
