### ISSUE TITLE
RHVoice engine crashes

### ISSUE THREAD

**Issue by mrchen077** [Olga-Yakovleva/RHVoice#198]
Android - multiple versions
RHVoice: ver 1.2.2
Voice: any
TTS Reader: Reedy ver 3.2.4.51

To reproduce - paste the following text into the reader (or create a text file with this text) and activate RHVoice engine:

Вот сейчас, на этой самой машине? А?!
 «И действительно, — вдруг с прежней легкостью

The engine crashes before reading "«И действительно"

**Comment by Olga-Yakovleva** [comment]
I'd like to confirm that it can be reproduced with the latest code.
@mrchen077 could you test this build?
https://dl.bintray.com/olga-yakovleva/Android/RHVoice-v1.2.3.apk

**Comment by mrchen077** [comment]
I tested build 1.2.3
https://dl.bintray.com/olga-yakovleva/Android/RHVoice-v1.2.3.apk
and the problem is still there - the engine crashes before reading "«И действительно"

Please can you make sure you are testing it with  Reedy ver 3.2.4.51 because this is what I am using.

**Comment by Olga-Yakovleva** [comment]
Well, I've installed Reedy, the same version, but still no luck
reproducing. Are you quoting the whole last sentence? Can you quote
some more text after it, basically, just give me the whole paragraph
and, if that paragraph ends in that sentence, the next one as well for
good measure.

**Comment by mrchen077** [comment]
I attach the original ebook and two screenshots of four bookmarks where RHVoice crashes. The first crash is in the beginning of the book, just before the embedded image.

[popov.fb2.zip](https://github.com/Olga-Yakovleva/RHVoice/files/5208176/popov.fb2.zip)
![popov_bookmarks1](https://user-images.githubusercontent.com/45572026/92908074-cdab3580-f41d-11ea-96e2-d3225c8d1548.jpg)
![popov_bookmarks2](https://user-images.githubusercontent.com/45572026/92908077-ce43cc00-f41d-11ea-8630-3c6f5679c4a7.jpg)

**Comment by Olga-Yakovleva** [comment]
Screenshots are no use to me, as I'm totally blind. So, what should I
do to reproduce? Is it right at the beginning, so I may just start
playing the book from the start?

**Comment by Olga-Yakovleva** [comment]
I tried it just in case, but playing a few first sentences didn't
result in a crash. So please provide detailed instructions in words
how to get close to one of those crash points in the book.

**Comment by Olga-Yakovleva** [comment]
OK, there is a search function, so I have found your quote. Yes, there
is a problem. I will investigate.

**Comment by mrchen077** [comment]
Playing the book from the start should do it as the first bookmark is close to the top, just before the embedded image. I'll paste other bookmarks as text here if necessary.

**Comment by Olga-Yakovleva** [comment]
Whatever it is, it also happens with Google TTS and Vocalizer, so it doesn't seem to be a problem with RHVoice. Closing.
