### ISSUE TITLE
Cross compilation completely fails to work

### ISSUE THREAD

**Issue by katyo** [Olga-Yakovleva/RHVoice#20]
When I tried to build package in cross-compilation environment, I've found that I can't to do it because $CC and $CXX environment variables, which I set for, is useless for this scons build rules. Also, there is no another ways to do same thing. Anyway I don't know how to do it without patching build rules.

**Comment by katyo** [comment]
I tried to add variables:
```
vars.Add("CC","C compiler","cc")
vars.Add("CXX","C++ compiler","c++")
vars.Add("PATH","System paths",os.environ["PATH"])
```
after
```
vars=Variables(var_cache,args)
```

But scons failed with:
```
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... no
The C compiler is not working
```

I'm not an expert in scons, so I don't know how to get verbose output from it.

**Comment by techtonik** [comment]
@katyo try `scons -H`, but can't see what will help there.

Try dumping environment with `print base_env.Dump()` after variables are added to it. I am not sure how Variables mechanism work, and it may happen that they are added to environment only after     `env_args["variables"]=vars`

Also, check `build/linux/configure.log` and other files for troubleshooting.

**Comment by katyo** [comment]
It seems this problem is solved:

```
vars.Add("CC","C compiler","cc")
vars.Add("CXX","C++ compiler","c++")
vars.Add("ENV","Build environment",{
  "PATH":os.environ["PATH"],
  "STAGING_DIR":os.environ["STAGING_DIR"]
})
```

**Comment by techtonik** [comment]
That's good. PR or.. close the ticket?

**Comment by alyoshin** [comment]
[0001-Add-targetcross-CSons-variable.patch.zip](https://github.com/Olga-Yakovleva/RHVoice/files/3908425/0001-Add-targetcross-CSons-variable.patch.zip)

**Comment by techtonik** [comment]
@alyoshin send PR?

**Comment by alyoshin** [comment]
https://github.com/Olga-Yakovleva/RHVoice/pull/122
