### ISSUE TITLE
swedish voice?

### ISSUE THREAD

**Issue by mjonsson1986** [Olga-Yakovleva/RHVoice#208]
are possible to get a swedish voice?

**Comment by alex19EP** [comment]
if you can implement this.

**Comment by mjonsson1986** [comment]
i'm not a developer


Den 14 oktober 2020 14:42:52 skrev Alexander Epaneshnikov 
<notifications@github.com>:

**Comment by alex19EP** [comment]
I understand. 
creating a new voice, or language is very difficult process.
and now we do not accept such requests.

I'm sorry.
