### ISSUE TITLE
Eliminate network permissions and voice data downloading code from Android app

### ISSUE THREAD

**Issue by KOLANICH** [Olga-Yakovleva/RHVoice#211]
Currently the Android app has too broad permissions. One of the needs for them is because it downloads voices from the Net. BTW, downloading voices from the Net ourselves may have issues related to support of TLS in old devices.

The proposal is to move voices into separate packages, use android.content.pm.PackageManager to load their content and use a store app (F-Droid, Google Play, other stores...) to update them, eliminating the logic and the permissions to access the Net from RHVoice app.

**Comment by beqabeqa473** [comment]
i think voices and languages should have a separate server api to be
listed and downloaded by rhvoice android client.

this makes publishing new and updates voices and voices and updated
language data faster, as publication of apps in google play is not so
fast and this pandemic situation makes it slower and updates and new
apps are processing slower.

On 10/17/20, KOLANICH <notifications@github.com> wrote:
> Currently the Android app has too broad permissions. One of the needs for
> them is because it downloads voices from the Net. BTW, downloading voices
> from the Net ourselves may have issues related to support of TLS in old
> devices.
>
> The proposal is to move voices into separate packages, use
> android.content.pm.PackageManager to load their content and use a store app
> (F-Droid, Google Play, other stores...) to update them, eliminating the
> logic and the permissions to access the Net from RHVoice app.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/211


-- 
with best regards beqa

**Comment by KOLANICH** [comment]
>i think voices and languages should have a separate server api to be listed and downloaded by rhvoice android client.

I think that the engine should support voices sideloading by dropping them into a dir on sdcard. And instead of API just a HTML page with links to archives and a link to it in the app. No JavaScript! A user can download the language using the browser he likes and unpack it himself. Let's keep 🪰 separate from 🥩 (there is no emoji for котлета). I mean networking from synthesis, to make everyone sure that the app cannot send the texts spoken to the web or cannot download malware from the net and additionally to eliminate all the networking-related issues.

**Comment by beqabeqa473** [comment]
see #200 for more details.

On 10/17/20, KOLANICH <notifications@github.com> wrote:
>>i think voices and languages should have a separate server api to be listed
>> and downloaded by rhvoice android client.

>

> I think that the engine should support voices sideloading by dropping them
> into a dir on sdcard. And instead of API just a HTML page with links to
> archives and a link to it in the app. No JavaScript! A user can download the
> language using the browser he likes and unpack it himself. Let's keep 🪰
> separate from 🥩 (there is no emoji for котлета). I mean networking from
> synthesis, to make everyone sure that the app cannot send the texts spoken
> to the web or cannot download malware from the net and additionally to
> eliminate all the networking-related issues.

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/Olga-Yakovleva/RHVoice/issues/211#issuecomment-710930204


-- 
with best regards beqa

**Comment by Olga-Yakovleva** [comment]
No, we used to have separate apps for voices and languages, and I
implemented this current code specifically to avoid dealing with them.
Each new app on Google Play needs to be maintained separately. Every
time a developer needs to do all that manual work. I have no desire to
spend my time on that.

And there shouldn't be any problems with TLS on older devices. RHVoice
uses [Conscrypt](https://github.com/google/conscrypt) directly,
without relying on Play Services.

**Comment by Olga-Yakovleva** [comment]
Closing, as I'm not going to implement what is stated in the description of this issue.

**Comment by KOLANICH** [comment]
> added the (S4 - Invalid) 

It is not actually `invalid`, it is just `wontfix`
