### ISSUE TITLE
Установка на CentOs 6.5

### ISSUE THREAD

**Issue by svd-762** [Olga-Yakovleva/RHVoice#22]
Добрый день.
Пытаюсь поставить RHV на CentOs 6.5. В логе (build/linux/configure.log) вижу следующее:

```
$ tail -n3 build/linux/configure.log 
cc1plus: error: unrecognized command line option "-std=c++03"
scons: Configure: no
```

Файл (SConstruct) изменил следующим образом: 

``` ruby
110         vars.Add("prefix","Installation prefix","/usr")
...
115         vars.Add("sysconfdir","A directory for configuration files","/etc")
...
133     env = Environment()
134     env.Replace(CXX = "/opt/centos/devtoolset-1.1/root/usr/bin/gcc")
135     env.Replace(CC = "/opt/centos/devtoolset-1.1/root/usr/bin/cc")
136     env.Replace(CPP = "/opt/centos/devtoolset-1.1/root/usr/bin/c++")
137     env.Replace(LINK = "/opt/centos/devtoolset-1.1/root/usr/bin/g++")
138     cc = env['CC']
139     if cc == 'cl':
140         env.Append(CPPFLAGS = '/Wall')
141     elif cc == 'gcc':
142         env.Append(CCFLAGS = '-Wall')
```

Пути:

```
$ which g++
/opt/centos/devtoolset-1.1/root/usr/bin/g++
$ which c++
/opt/centos/devtoolset-1.1/root/usr/bin/c++
$ which cc
/opt/centos/devtoolset-1.1/root/usr/bin/cc
$ which gcc
/opt/centos/devtoolset-1.1/root/usr/bin/gcc
```

Версия компилятора:

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/centos/devtoolset-1.1/root/usr --mandir=/opt/centos/devtoolset-1.1/root/usr/share/man --infodir=/opt/centos/devtoolset-1.1/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --disable-build-with-cxx --disable-build-poststage1-with-cxx --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-ppl --with-cloog --with-mpc=/home/centos/rpm/BUILD/gcc-4.7.2-20121015/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC) 
```

Спасибо.

**Comment by nshmyrev** [comment]
> "Что я делаю не так?"

Развели на машине компиляторов зоопарк, а потом пишите бедной девушке о своих личных проблемах вместо того, чтобы FAQ по scons почитать.

> И в какую сторону копать?

Прочесть

https://bitbucket.org/scons/scons/wiki/FrequentlyAskedQuestions#markdown-header-why-doesnt-scons-find-my-compilerlinkeretc-i-can-execute-it-just-fine-from-the-command-line

потом следовать инструкциям.

**Comment by beqabeqa473** [comment]
а чтоже вы G++ не поставите а?

**Comment by svd-762** [comment]
Так. Давайте без понтов. Зооопарк я развел только потому, что по дефолту (4.4.7) RHV не собирается, Я бы не разводил ни какого "зоопарка" если бы софт собирался на дефолте. 

Образно выражаясь, мой зоопарк - был вариантом решения на *Checking whether the C++ compiler worksno* 

Стоит у меня GCC 4.4.7, с помощью которого собран asterisk 13.5.0.
Нагуглил,что ошибка - *cc1plus: error: unrecognized command line option "-std=c++03"* говорит от том, что компилятор древний. От сюда и зоопарк...

p.s. Ни на кого я не наезжаю. Тут ищу только помощи. Касательно "прочесть" - Иди в жопу. Ибо не ГУРУ.

**Comment by svd-762** [comment]
В общем. Не надо отправлять меня на RTFM, если не можете помочь в решении моей проблемы. Ибо RTFM  я читал прежде, чем написать сюда. Привычка такая.

**Comment by svd-762** [comment]
Ну и про - "ЧТО ВЫ G++ НЕ ПОСТАВИТЕ"

[just@ast ~]$ g++ -v
Используются внутренние спецификации.
Целевая архитектура: x86_64-redhat-linux
Параметры конфигурации: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Модель многопоточности: posix
gcc версия 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 

[just@ast ~]$ g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
Это свободно распространяемое программное обеспечение. Условия копирования
приведены в исходных текстах. Без гарантии каких-либо качеств, включая 
коммерческую ценность и применимость для каких-либо целей.

Ну, может этого мало??? Тогда так:
[just@ast ~]$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/centos/devtoolset-1.1/root/usr --mandir=/opt/centos/devtoolset-1.1/root/usr/share/man --infodir=/opt/centos/devtoolset-1.1/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --disable-build-with-cxx --disable-build-poststage1-with-cxx --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-ppl --with-cloog --with-mpc=/home/centos/rpm/BUILD/gcc-4.7.2-20121015/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC) 

[just@ast ~]$ g++ --version
g++ (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Еще раз... Я бы не писал сюда, если  бы не мог решить данной  проблемы...

**Comment by abitrolly** [comment]
@svd-762 для начала стоит прочитать пункт 8 правил чудесного документа https://help.github.com/articles/github-terms-of-service/#g-general-conditions и привести свои сообщения в первую нормальную форму. Иначе нет смысла отвечать в удалённый тред удалённому аккаунту.

**Comment by abitrolly** [comment]
> Не надо отправлять меня на RTFM, если не можете помочь в решении моей проблемы.

У меня не стоит CentOS и соответственно, нет с ней проблемы. Телепаты в отпуске, а в этом чудесном потоке вывода я не вижу ответа на вопрос, с какой версии GCC поддерживается опция `-std=c++03`?

Потом, какой реально компилятор используется `scons`? Должно помочь что-то типа:
```
env = Environment()
print(env['CC'])
```

Потом, читать SO как указать правильный, если буква F в RTFM слишком грубо
http://stackoverflow.com/questions/2944251/changing-default-compiler-in-linux-using-scons
или попробовать указать настройки
http://stackoverflow.com/questions/1961164/how-can-i-set-options-in-sconstruct-for-c-compiler-depending-on-compiler-type,
Если English непонятен, то в этом нет ничего стыдного. Это как курение - вредно для здоровья, но спросить сигаретку никто не мешает. Если вежливо.

**Comment by svd-762** [comment]
Приношу свои **искренние извинения**. Не прав.
Текст исправил, эмоции и то, что не по делу - удалил.

to @abitrolly 
> Потом, какой реально компилятор используется scons? Должно помочь что-то типа:

Просто пишет одно слово: **gcc** Происходит это потому, что файлов с таким именем - два.
```
/usr/bin/gcc (4.4.2)
//opt/centos/devtoolset-1.1/root/usr/bin/gcc (4.7.2)
```

Перед тем, как запустить **scons**, выполняю следующие команды:
```
$ scl enable devtoolset-1.1 bash
$ export CC=/opt/centos/devtoolset-1.1/root/usr/bin/gcc  
$ export CPP=/opt/centos/devtoolset-1.1/root/usr/bin/cpp
$ export CXX=/opt/centos/devtoolset-1.1/root/usr/bin/c++
```
Ну и путь в переменной окружения тоже присутствует.

**Comment by abitrolly** [comment]
@svd-762 SCons игнорирует системное окружение. Environment в SCons - это свой собственный Environment. Судя по коду ты об этом в курсе. :)

Было бы проще увидеть .diff в отдельном коммите, потому что я не вижу контекста - после:

    env = Environment()
    env.Replace(CC = "/opt/centos/devtoolset-1.1/root/usr/bin/cc")

SCons на `print(env['CC'])` не может выводить `gcc`. По-крайней мере следующей строчкой. `env` здесь - это не интерфейс к глобальному состоянию - это новый объект, и если ты его не передаешь дальше, то информация теряется.

Я бы добавлял `print(env['CC'])` в конкретный SConcript в директории где компилятор валится и устанавливал настройки там же.

**Comment by svd-762** [comment]
@abitrolly Спасибо за ответ и помощь. Я уже было подумал, что всё, остался сам на сам.
Понял, что вставил код не в то место файла и он просто не выполнялся потому, как scons завершался выше, когда не находил gcc. Но это всё равно не помогло...

Перенёс код в начало файла SConstruct. Ниже показан выхлоп diff. **.bk** - оригинал, стянутый git-ом.

```ruby
$ diff SConstruct SConstruct.bk 
23,30d22
< env=Environment()
< env.Replace(CXX = "/opt/centos/devtoolset-1.1/root/usr/bin/gcc")
< env.Replace(CC = "/opt/centos/devtoolset-1.1/root/usr/bin/cc")
< env.Replace(CPP = "/opt/centos/devtoolset-1.1/root/usr/libexec/gcc/x86_64-redhat-linux/4.7.2/cc1plus")
< env.Replace(LINK = "/opt/centos/devtoolset-1.1/root/usr/bin/g++")
< cc = env['CC']
< print(cc)
< 
110,111d101
< 
< 
120c110
<         vars.Add("prefix","Installation prefix","/usr")
---
>         vars.Add("prefix","Installation prefix","/usr/local")
125c115
<         vars.Add("sysconfdir","A directory for configuration files","/etc")
---
>         vars.Add("sysconfdir","A directory for configuration files","$prefix/etc")
```

Ну, и собственно, сам **print()**

```ruby
$ scons
scons: Reading SConscript files ...
/opt/centos/devtoolset-1.1/root/usr/bin/cc
Mkdir("build/linux")
Checking whether the C compiler worksyes
Checking whether the C++ compiler worksno
The C++ compiler is not working
```
Пытался вставить в то место, где возникает ошибка. Точнее перед ним. Так и не смог. Я не знаю особенностей структуры этого файла и всякий раз, куда бы я не вставлял эти несчастные четыре строчки (кроме начала файла), всякий раз возникают ошибки типа:

```ruby
$ scons
scons: Reading SConscript files ...
  File "/home/just/RHVoice/SConstruct", line 194

    conf=env.Configure(conf_dir=os.path.join(env["BUILDDIR"],"configure_tests"),

                                                                               ^

IndentationError: unindent does not match any outer indentation level

$ vim SConstruct 
$ scons
scons: Reading SConscript files ...
  File "/home/just/RHVoice/SConstruct", line 194

    conf=env.Configure(conf_dir=os.path.join(env["BUILDDIR"],"configure_tests"),

   ^

IndentationError: unexpected indent

$ vim SConstruct 
$ scons
scons: Reading SConscript files ...
  File "/home/just/RHVoice/SConstruct", line 197

    if not conf.CheckCC():

                         ^

IndentationError: unindent does not match any outer indentation level

$ vim SConstruct 
$ scons
scons: Reading SConscript files ...
  File "/home/just/RHVoice/SConstruct", line 194

    conf=env.Configure(conf_dir=os.path.join(env["BUILDDIR"],"configure_tests"),

   ^

IndentationError: unexpected indent
```

Ну и **print(env['CC'])**, размещенный непосредственно после **print "The C++ compiler is not working"**, выдает **gcc**

```ruby
$ scons
scons: Reading SConscript files ...
/opt/centos/devtoolset-1.1/root/usr/bin/cc
Mkdir("build/linux")
Checking whether the C compiler worksyes
Checking whether the C++ compiler worksno
The C++ compiler is not working
gcc
```
Был бы признателен, если бы вы явно указали то место в коде, где нужно внести изменения...

**Comment by abitrolly** [comment]
Форкни репозиторий и закоммить в свою версию - так лучше видно.

Потом, SConstruct - это чистый питон. Потратишь две недели на изучение - сэкономишь пару месяцев жизни. Питон чувствителен к отступам. Отсутпы в Питоне - часть языка. Точнее вложенные блоки в нём - это отступы. Для незрячих - это проблема, но для остальных должно быть проще. Так что просто вставь строки с отступом, который согласуется со строками вокруг.

Когда ты выполняешь `env=Environment()` - ты создаешь свой Environment, а тебе надо модифицировать уже созданный. Я буду тренироваться быть вежливым и терпеливым и поэтому скажу, что это происходит в функции `create_base_env` в строке `env=Environment(**env_args)`.

Потом в директории `build/config.log` должна быть подробная информация что там как запускается в CheckCXX и с каким кодом ошибки вываливается.

**Comment by abitrolly** [comment]
@svd-762 и вообще попробуй из этого репозитория собрать - https://github.com/cubicrobotics/RHVoice/commit/d861780128ec4117472a0fe504dab50a39e2fc3b

**Comment by svd-762** [comment]
Снёс все нафиг, скачал заново, изменил SConstruct. Нашел строку, содержащую слово  **Environment**. ( Спасибо за подсказки @abitrolly )
```ruby
145     env=Environment(**env_args)
```
Вставив после неё следующие строки:
```ruby
146     env.Replace(CXX = "/opt/centos/devtoolset-1.1/root/usr/bin/gcc")
147     env.Replace(CC = "/opt/centos/devtoolset-1.1/root/usr/bin/cc")
148     env.Replace(CPP = "/opt/centos/devtoolset-1.1/root/usr/bin/c++")
149     env.Replace(LINK = "/opt/centos/devtoolset-1.1/root/usr/bin/g++")
```

Компилятор нашелся, но опять таки сборка прервалась очередными ошибками:
```ruby
$ scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler worksyes
Checking whether the C++ compiler worksyes
Checking for pkg-config... yes
ValueError: zero length field name in format:
  File "/home/just/RHVoice/SConstruct", line 295:
    build_for_linux(base_env)
  File "/home/just/RHVoice/SConstruct", line 247:
    build_binaries(base_env)
  File "/home/just/RHVoice/SConstruct", line 239:
    src_subdirs=configure(env)
  File "/home/just/RHVoice/SConstruct", line 210:
    if conf.CheckPKG("libpulse-simple"):
  File "/usr/lib/scons/SCons/SConf.py", line 640:
    ret = self.test(context, *args, **kw)
  File "/home/just/RHVoice/SConstruct", line 40:
    context.Message("Checking for {}... ".format(name))
```
В общем я устал изображать из себя питонщика... Кто нибудь, кто ставил RHV на CentOS, расскажите что конкретно правили? А то, что RHV не собирается под RH без напильника - походу факт...

**Comment by abitrolly** [comment]
@svd-762 какая версия Python?

**Comment by svd-762** [comment]
> @svd-762 какая версия Python?
```ruby
$ python --version
Python 2.6.6
```

**Comment by abitrolly** [comment]
@svd-762 этой версии уже 5 лет, а Ольга писала скрипт на 2.7. Возьми операционку поновее, потому что уже мало кто на Python 2.6 тестирует.

**Comment by svd-762** [comment]
> этой версии уже 5 лет, а Ольга писала скрипт на 2.7. Возьми операционку поновее, потому что уже мало кто на Python 2.6 тестирует.

Без вариантов. Это рабочий сервер. Но я тебя понял. Спасибо за помощь.

**Comment by abitrolly** [comment]
Ну извини уж - ковыряться с чужими рабочими серверами в свободное время у меня нет ни денег, ни желания. Если очень хочется, то можешь поменять:

    context.Message("Checking for {}... ".format(name))

на

    context.Message("Checking for %s... " % name)

Но вообще найми себе питонщика, чтобы не тратить время на изучение устаревшей ветки 2.6.

**Comment by svd-762** [comment]
Нормально все, Анатолий. Не за что извиняться. Спасибо еще раз за помощь и за уделённое для меня время.

**Comment by svd-762** [comment]
@abitrolly
Впрочем обновил питона до 2.7.5. Как узнать какую версию использует scons? Как указать явно?
```ruby
$ python --version
Python 2.7.5
```

**Comment by abitrolly** [comment]
Узнать версию:

    import sys
    print sys.version

Явно указать (если `scons` на CentOS установлен как Python скрипт, а не бинарник)

    python `which scons`

**Comment by svd-762** [comment]
Ага. Прогресс есть. Начал собираться. Только не находит нужные библиотеки и, как следствие, нет **RHVoice-client**. Как явно указать на питоне, где их искать? Или может нужны конкретные версии?
```ruby
$ python `which scons` --clean
scons: Reading SConscript files ...
2.7.5 (default, Jul 10 2014, 16:10:08) 
[GCC 4.7.2 20121015 (Red Hat 4.7.2-5)]
Mkdir("build/linux")
Checking whether the C compiler works(cached) yes
Checking whether the C++ compiler works(cached) yes
Checking for pkg-config... (cached) yes
Checking for libpulse-simple... (cached) yes
Checking for ao... (cached) no
Checking for portaudio-2.0... (cached) no
Checking for giomm-2.4... (cached) no
```
```
Installed Packages
libao-devel.x86_64      0.8.8-7.1.el6
portaudio-devel.x86_64  19-9.el6
glibmm24-devel.x86_64   2.22.1-1.el6
```

**Comment by abitrolly** [comment]
Все проверки конспектируются в `build/config.log`

**Comment by shalugin** [comment]
Здравствуйте!

Получилось ли собрать? У меня сейчас такая ошибка:

```
[root@localhost RHVoice]# python2.7 `which scons`
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works(cached) yes
Checking whether the C++ compiler works(cached) yes
Checking for pkg-config... (cached) yes
Checking for libpulse-simple... (cached) yes
Checking for ao... (cached) yes
Checking for portaudio-2.0... (cached) yes
Checking for giomm-2.4... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
/opt/centos/devtoolset-1.1/root/usr/bin/gcc -o build/linux/service/client.o -c -std=c++03 -O2 -pthread -DRHVOICE=1 -DPACKAGE=\"RHVoice\" -DVERSION=\"0.5.1\" -Ibuild/linux/service -Isrc/service -Isrc/include -Isrc/third-party/utf8 -Isrc/third-party/tclap -Isrc/third-party/sonic -Isrc/third-party/rapidxml -Isrc/third-party/mage -Isrc/third-party/hts_engine -I/usr/include/giomm-2.4 -I/usr/lib64/giomm-2.4/include -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include src/service/client.cpp
src/service/client.cpp:72:16: error: 'DBus' is not a member of 'Gio'
src/service/client.cpp:72:16: error: 'DBus' is not a member of 'Gio'
src/service/client.cpp:72:37: error: template argument 1 is invalid
src/service/client.cpp:72:49: error: invalid type in declaration before ';' token
src/service/client.cpp:73:16: error: 'DBus' is not a member of 'Gio'
src/service/client.cpp:73:16: error: 'DBus' is not a member of 'Gio'
src/service/client.cpp:73:32: error: template argument 1 is invalid
src/service/client.cpp:73:39: error: invalid type in declaration before ';' token
src/service/client.cpp: In function 'void {anonymous}::call_method(const Glib::ustring&)':
src/service/client.cpp:101:10: error: base operand of '->' is not a pointer
src/service/client.cpp: In function 'void {anonymous}::call_method(const Glib::ustring&, const T&)':
src/service/client.cpp:107:5: error: 'Variant' is not a member of 'Glib'
src/service/client.cpp:107:20: error: expected primary-expression before '>' token
src/service/client.cpp:107:22: error: 'var_arg' was not declared in this scope
src/service/client.cpp:107:30: error: 'Variant' is not a member of 'Glib'
src/service/client.cpp:107:45: error: expected primary-expression before '>' token
src/service/client.cpp:107:46: error: '::create' has not been declared
src/service/client.cpp:108:5: error: 'VariantContainerBase' is not a member of 'Glib'
src/service/client.cpp:108:32: error: expected ';' before 'var_args'
src/service/client.cpp:109:10: error: base operand of '->' is not a pointer
src/service/client.cpp:109:27: error: 'var_args' was not declared in this scope
src/service/client.cpp: In function 'void {anonymous}::call_method(const Glib::ustring&, const T1&, const T2&)':
src/service/client.cpp:115:17: error: 'VariantBase' is not a member of 'Glib'
src/service/client.cpp:115:17: error: 'VariantBase' is not a member of 'Glib'
src/service/client.cpp:115:34: error: template argument 1 is invalid
src/service/client.cpp:115:34: error: template argument 2 is invalid
src/service/client.cpp:115:40: error: invalid type in declaration before ';' token
src/service/client.cpp:116:10: error: request for member 'push_back' in 'args', which is of non-class type 'int'
src/service/client.cpp:116:20: error: 'Variant' is not a member of 'Glib'
src/service/client.cpp:116:36: error: expected primary-expression before '>' token
src/service/client.cpp:116:37: error: '::create' has not been declared
src/service/client.cpp:117:10: error: request for member 'push_back' in 'args', which is of non-class type 'int'
src/service/client.cpp:117:20: error: 'Variant' is not a member of 'Glib'
src/service/client.cpp:117:36: error: expected primary-expression before '>' token
src/service/client.cpp:117:37: error: '::create' has not been declared
src/service/client.cpp:118:5: error: 'VariantContainerBase' is not a member of 'Glib'
src/service/client.cpp:118:32: error: expected ';' before 'var_args'
src/service/client.cpp:119:10: error: base operand of '->' is not a pointer
src/service/client.cpp:119:27: error: 'var_args' was not declared in this scope
src/service/client.cpp: At global scope:
src/service/client.cpp:172:26: error: 'VariantContainerBase' in namespace 'Glib' does not name a type
src/service/client.cpp:172:54: error: ISO C++ forbids declaration of 'params' with no type [-fpermissive]
src/service/client.cpp: In function 'void {anonymous}::write_audio(const int&)':
src/service/client.cpp:176:5: error: 'Variant' is not a member of 'Glib'
src/service/client.cpp:176:34: error: expected primary-expression before '>' token
src/service/client.cpp:176:36: error: 'vsamples' was not declared in this scope
src/service/client.cpp:177:12: error: request for member 'get_child' in 'params', which is of non-class type 'const int'
src/service/client.cpp: At global scope:
src/service/client.cpp:182:85: error: 'VariantContainerBase' in namespace 'Glib' does not name a type
src/service/client.cpp:182:113: error: ISO C++ forbids declaration of 'params' with no type [-fpermissive]
src/service/client.cpp: In function 'void {anonymous}::on_dbus_proxy_available(Glib::RefPtr<Gio::AsyncResult>&)':
src/service/client.cpp:194:20: error: 'Gio::DBus' has not been declared
src/service/client.cpp:195:14: error: base operand of '->' is not a pointer
src/service/client.cpp: In function 'int main(int, const char**)':
src/service/client.cpp:228:23: error: 'Gio::DBus' has not been declared
src/service/client.cpp:228:55: error: 'Gio::DBus' has not been declared
src/service/client.cpp:235:8: error: 'Gio::DBus' has not been declared
scons: *** [build/linux/service/client.o] Error 1
scons: building terminated because of errors.
```

**Comment by Arhzi** [comment]
> glibmm24-devel.x86_64   2.22.1-1.el6

Нужна версия минимум 2.36. Где взять: пока не нашел в репах. Видимо придется компилировать ручками.
