### ISSUE TITLE
RHVoice vs gnuspeach

### ISSUE THREAD

**Issue by seniorivn** [Olga-Yakovleva/RHVoice#23]
http://www.opennet.ru/opennews/art.shtml?num=43168
этот движок лучше или хуже вашего? не хотите влиться в разработку гнутого проекта? сделать ему русскую версию.

**Comment by abitrolly** [comment]
Как тебе сказать, лучше или хуже - понятие субъективное. Для русского RHVoice однозначно лучше. От GNU Speech мне понравились бумажки про TRM, но пока это всё. Качество звука в доступных примерах на инглише меня не впечатлило, а для последней версии я их вообще не нашёл.

Да и в интернете gnuspeech не жалуют - https://news.ycombinator.com/item?id=10422823 и http://superuser.com/questions/42361/good-voice-syntheses-for-linux

**Comment by seniorivn** [comment]
Спасибо, то что сейчас результат синтеза у rhvoice на русском лучше всех(свободных) это точно, а у festival на других языках, но мой вопрос скорее про архитиктуру, быть может у гнутого проекта большой потенциал, не зря же они релиз выкатили :)

**Comment by abitrolly** [comment]
:) Гнутые проекты типа GNU Radio - они клёвые, но про потенциал остальных сложно говорить. Иногда это наоборот - уже устарешвася и ложная цель, которая тратит много суммарного времени, как, например, Autotools. Потом я совсем не вижу экономической модели за гнутостью. GNU системы рождались во время, когда технологии контроля занятости сотрудников ещё не были столь совершенны, и у людей было свободное время использовать свои профессиональные навыки, чтобы нести пользу людям. Сейчас я не знаю людей, которые могут себе это позволить. Я лично пытался написать заявку на грант, чтобы добавить белорусский язык в RHVoice и мануал по созданию языков, но не осилил. Все клёвые вещи делаются командами, а команда работает только тогда, когда есть время на синхронизацию.

От GNU Speech было бы интересно скрестить TRM с HMM, но из-за того, что у Ольги физически мало возможностей для сопровождения open source проекта, нам приходится много чего постигать самим. В этом плане потенциал у самого RHVoice не слишком высоких. В основном он создаётся за счёт живого интереса незрячих пользователей в результате, и они клёвые ребята - им хочется помогать, потому что ты видишь/чувствуешь, что им это надо и они реально помогают.. если знать что делать.

 Я вот только что узнал про MaryTTS из HN, и если говорить про перспективу, то вот прямо сейчас по информации с их сайта - я бы работал с ними.

**Comment by abitrolly** [comment]
У архитектуры gnuspeech есть самое главное, чего не хватает многим проектам - клёвая понятная диаграмма этой самой архитектуры. Если бы у RHVoice была такая же - мы могли бы сравнивать. :)

**Comment by CHERTS** [comment]
А можно спросить, почему качество синтеза RHVoice под Windows и Android сильно различаются? Под Android качество синтеза просто ужасное, по сравнению с Windows.
P.S. Я пробовал на примере одного и того же голоса.

**Comment by abitrolly** [comment]
@CHERTS я не разработчик, но вообще на Android-платформе не у всех элитные прозводительные планшеты - многие покупают китайские. Потом, RHVoice под Android - насколько я в курсе, это не какая-то там финальная версия, и поэтому все возможности платформ она вряд ли использует. Вообще сейчас речевой синтез делают на GPU, но я не знаю, каким надо быть гуру, чтобы запилить синтез звукового сигнала через текстуры и треугольники OpenGL ES.

**Comment by seniorivn** [comment]
@CHERTS  не имею никакого отношения к каким либо синтезаторам речи и даже к этим технологиям очень посредственное, но я думаю в такой задаче использовался бы opencl, а не opengl

**Comment by Oire** [comment]
Народ, вы тут в такие дебри ушли, что прям вообще :). А я вот спрошу с юзерской точки зрения: как оно вообще, качество этого самого GnuSpeech на слух?

**Comment by abitrolly** [comment]
@seniorivn а OpenCL по-ходу гуглом блокируется - http://stackoverflow.com/questions/14385843/why-did-google-choose-renderscript-instead-of-opencl

**Comment by abitrolly** [comment]
@Oire не знаю как звучит последняя версия, бо нет линукса под рукой, но то что в инете нахожу - не очень. Может привыкнуть надо.
