### ISSUE TITLE
scons: sapi5 Installers - cannot find WiX and NSIS

### ISSUE THREAD

**Issue by beqabeqa473** [Olga-Yakovleva/RHVoice#231]
in commit e5f1b23
it is no longer possible to run build process
KeyError: 'WindowsInstallers_core_64':
File "C:\Users\beqap\git-repos\rhvoice\SConstruct", line 357:
build_for_windows(base_env,vars)
File "C:\Users\beqap\git-repos\rhvoice\SConstruct", line 337:
SConscript(os.path.join("data","SConscript"),
File "c:\python\python39-32\lib\site-packages\SCons\Script\SConscript.py", line 661:
return method(*args, **kw)
File "c:\python\python39-32\lib\site-packages\SCons\Script\SConscript.py", line 598:
return _SConscript(self.fs, *files, **subst_kw)
File "c:\python\python39-32\lib\site-packages\SCons\Script\SConscript.py", line 287:
exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
File "C:\Users\beqap\git-repos\rhvoice\data\SConscript", line 79:
packagers["exe"].msis.append(local_env["WindowsInstallers_core_64"])
File "c:\python\python39-32\lib\site-packages\SCons\Environment.py", line 405:
return self._dict[key]
i have WiX and NSIS installed

**Comment by beqabeqa473** [comment]
i saw @alex19EP reverted problematic pr earlier, so no problem in this part, however it would be better to test changes before pushing.

Closely related to this issue.

e5f1b2372ca7ece6ab31e3f6e8a9bba7a685e41f
it is no longer possible to run build process

KeyError: 'WindowsInstallers_core_64':
  File "C:\Users\beqap\git-repos\rhvoice\SConstruct", line 357:
    build_for_windows(base_env,vars)
  File "C:\Users\beqap\git-repos\rhvoice\SConstruct", line 337:
    SConscript(os.path.join("data","SConscript"),
  File "c:\python\python39-32\lib\site-packages\SCons\Script\SConscript.py", line 661:
    return method(*args, **kw)
  File "c:\python\python39-32\lib\site-packages\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "c:\python\python39-32\lib\site-packages\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\Users\beqap\git-repos\rhvoice\data\SConscript", line 79:
    packagers["exe"].msis.append(local_env["WindowsInstallers_core_64"])
  File "c:\python\python39-32\lib\site-packages\SCons\Environment.py", line 405:
    return self._dict[key]


i have WiX and NSIS installed
@alex19EP please look at this.

**Comment by alex19EP** [comment]
> however it would be better to test changes before pushing.

yes. i know that. ci would help with that. but to enable it we should move rhvoice to own organization.

> Closely related to this issue.
e5f1b23
it is no longer possible to run build process

how nsys and wix are installed on your system? can you provide full build output? 

> this is not first and perhaps not last that changes from @KOLANICH makes problems and don't improve quality of end product.

i strongly disagree with this words. Moreover, I find them offensive towards the same contributor as you.

**Comment by beqabeqa473** [comment]
I have installed WiX and NSIS as usual.

i didn't have problems before this commit, so if something should be changed, it should be noted.

anyway, reverting this commit fixes issue and i don't thing we should make changes to build system and break others for rhvoice to be happy.

**Comment by alex19EP** [comment]
> 
> 
> I have installed WiX and NSIS as usual.
> 

can you provide environment variables related to wix and nsis?
for example: WIXTOOLPATH and NSISDIR

> i didn't have problems before this commit, so if something should be changed, it should be noted.

yes. but we don’t have, in principle, compilation documentation for Windows. I want to simplify this procedure. and create such documentation.

> anyway, reverting this commit fixes issue and i don't thing we should make changes to build system and break others for rhvoice to be happy.

but you understand that this is not a solution to the problem?

**Comment by beqabeqa473** [comment]
ok, if you explain me with arguments why i should add these environment variables, what will be improved in this case and why these measures was taken? no problem.

but now, this change is not improving anything and no, you are not simplifying build process in this case, you make people take one more "unnecessary" step.

**Comment by beqabeqa473** [comment]
anyway, with WIX installed, i already have environment variable called WIX. why i should add one more or rename this?

**Comment by alex19EP** [comment]
> ok, if you explain me with arguments why i should add these environment variables, what will be improved in this case and why these measures was taken? no problem.

🙁 can i look at your variables first?

> but now, this change is not improving anything and no, you are not simplifying build process in this case, you make people take one more "unnecessary" step.

I repeat. if you can provide me with a list of your environment variables, then maybe I can fix this error.
without variables, I can argue with you endlessly. I will note that I do not want this at all.

**Comment by beqabeqa473** [comment]
I have environment variable called WIX which was set by WIX installer.
i don't have any environment variables related to NSIS and don't se a reason to set one, because checking from registry works well.

do you need any more details?

**Comment by alex19EP** [comment]
yes what WIX contains?

> i don't have any environment variables related to NSIS and don't se a reason to set one, because checking from registry works well.

not all ways to install nsys modify registry.

**Comment by beqabeqa473** [comment]
WIX; C:\Program Files (x86)\WiX Toolset v3.11\
installing nsis usually always writes installed location in registry. if it is not in your case, that is your problem to fix.

**Comment by alex19EP** [comment]
> installing nsis usually always writes installed location in registry. if it is not in your case, that is your problem to fix.

try to install it wire [scoop](https://scoop.sh/). 😉

**Comment by beqabeqa473** [comment]
If you really want to simplify things, take an example from people from nvaccess and try to make virtual environment.

**Comment by beqabeqa473** [comment]
i use winget 🤣

**Comment by beqabeqa473** [comment]
i should repeat, "USUAL INSTALLATION". that is what most of people do. nsis installer doesn't set environment variables by default.

**Comment by alex19EP** [comment]
@beqabeqa473 please test #232

**Comment by beqabeqa473** [comment]
'"C:\Program Files (x86)\WiX Toolset v3.11\\candle.exe"' is not recognized as an internal or external command,
operable program or batch file.


in standard WIX installation executables are in directory called bin

**Comment by KOLANICH** [comment]
> @KOLANICH maybe it would be better to test changes on your own before making pull requests

I test my changes ... on my configuration ... sometimes (some of the last PRs weren't tested, since in isolation they don't work and build on my machine, I have splitted them in order to pand them to reduce probability of rebase conflicts). The purpose of beta-versions (not releases, releases reside in https://github.com/Olga-Yakovleva/RHVoice/releases ) is to test on everyones configurations, not to provide something that is guaranteedly bug-free. To cooperate to make the software beter. You can expect no bugs being introduced only in one case - nothing nontrivial is done.

We have different machines, and different use cases.

My configurations are:
	for Windows:
		MinGW-w64 8 (the one available on SourceForge as a prebuilt zip, sjlj exceptions model) + CMake (gcc from mingw and clang from the official website), Windows 7 32-bit (but I use it rarely).

	for Linux:
		gcc and clang from the latest Ubuntu.


So, my PRs are expected to be tested by the people. These people are expected to tell if anything had been broken for them. I gonna try to fix the bugs, but have no ETA, I work on the project in my spare time.

>and @alex19EP maybe you should confirm that pull request doesn't break anything before accepting.

We need to setup CI and testing somehow. Some wishes about CI:
* it should test with both MinGW-w64 and with VS
* it should test with both CMake and SCons
* it should publish an artifact after every build

@beqabeqa473, I currently have no plans to work on setting up CI, so contributions implementing CI are welcome. 

My current task is to make it work on Windows when built with free toolchains (without Visual Studio being installed) + CMake. I don't have Visual Studio (and I am not going to install it on my PC) and am unable to test on it. Also, I have written some scripts and have reused some CMake modules by other people in order to make it buildable with free toolchains. They have not be ported to scons, and I currently have no plans to do so. So currently one cannot build with a free toolchain with SCons, and contributions to fix that are also welcome.

**Comment by alex19EP** [comment]
@beqabeqa473  ok now. #232 should be working. 🤞

**Comment by beqabeqa473** [comment]
Ok, thanks for fix.
i left a comment in pr, it seems line was splitted accidentally.

anyway, previous behaviour was restored.
