### ISSUE TITLE
Installed Items Grouping in Windows Control Panel

### ISSUE THREAD

**Issue by Menelion** [Olga-Yakovleva/RHVoice#245]
Hi @Olga-Yakovleva and maintainers,

That seems to be a tiny issue but I don't see how to fix it so far.  
In Windows, when you install various RHVoice components and voices, they are interspersed in the Apps and Features applet, because all of them start from different letters, like the following:

```
aleksandr - Russian Voice for RHVoice
English Language Pack for RHVoice
SLT - English Voice for RHVoice
Russian Language Pack for RHVoice
```

and so on.  
When you try to remove all the stuff (say, to upgrade), it becomes an unnecessary complicated task.  
What I would love to see is that all of the items would start with RHVoice, like:

```
RHVoice Aleksandr, Russian Voice
RHVoice English Language Pack
```

and so on.  
I would be happy to submit a pull request for that, but either I don't know the code base well enough, or those data are not present in the repo.  
Any help is very much appreciated. Thanks!

**Comment by beqabeqa473** [comment]
hi @Menelion.

i've submitted #246
i've tested installers and nvda addons so RHVoice and its components are correctly groupped.
