### ISSUE TITLE
Can this speech SAPI5 voices on Linux? How can I use LTTS7 (Loquendo) voices with this? 

### ISSUE THREAD

**Issue by z3nth10n** [Olga-Yakovleva/RHVoice#247]
Hi,

I'd like to run this utility in order to speech texts using Loquendo LTTS7 voices on Linux. I have a huge mess trying to use Balabolka on Linux with Wine, but this is awful...

For this reason, I'd like t know if there is a possible solution for this on Linux with this utility or not.

Thanks!
PD: Is there available any Discord / gitter chat?

Best regards.

**Comment by alex19EP** [comment]
hello.

> I'd like to run this utility in order to speech texts using Loquendo LTTS7 

i don't understand how RHVoice related to Loquendo.

> For this reason, I'd like t know if there is a possible solution for this on Linux with this utility or not.

maybe you can install the synthesizer to vine, but I don't know how to do it. and I think that no one here knows this.

> PD: Is there available any Discord / gitter chat?

no.

**Comment by z3nth10n** [comment]
Thanks for your response!

I think I'll try: https://github.com/mjakal/sapi5_on_linux 😛

**Comment by z3nth10n** [comment]
I would like to ask something more. I have discovered that there are binaries for Linux in Loquendo. Could be these binaries used in Linux.

I would like to know if there is an option to use this on Linux which any method.

I share the question I posted on Stackoverflow to let you know which methods I tried: https://stackoverflow.com/questions/64934405/trying-to-find-the-original-loquendo-products-for-linux-not-windows

Thanks!

**Comment by abitrolly** [comment]
@z3nth10n you're using wrong tracker. RHVoice is not affiliated with Loquendo in any way. Write to their customer support if you're using their binaries.

**Comment by z3nth10n** [comment]
I know that this project doesn't have any relation to Loquendo, but maybe somebody has taken care of this.

I already tried that without luck, I'm waiting for a response by Nuance. But I think they won't answer.

Btw, I created this question: https://stackoverflow.com/questions/64940135/cant-cross-compile-c-program-using-loquendo-arm-libraries-shared-objects-so

**Comment by abitrolly** [comment]
@z3nth10n if they are not open source and don't answer, then why do you use them? :D
