### ISSUE TITLE
Не воспроизводит текст на русском

### ISSUE THREAD

**Issue by foozzi** [Olga-Yakovleva/RHVoice#25]
При выполнении команды: echo "Хотите выключить свет на кухне?" | RHVoice -W Elena | aplay
получаю ошибку:
```
bash: RHVoice: команда не найдена
aplay: playback:2715: read error
```
Компилировал без ошибок, все окей, ОС Chakra Linux (Arch linux), тест работает, но только на англ.:
```
echo day|RHVoice-test 
```
- Говорит
```
echo день|RHVoice-test 
```
- не говорит, пишет 
```
default Engine is default
```
Парни, подскажите, может быть где то я накосячил тут.

**Comment by abitrolly** [comment]
echo день|RHVoice-test 

Первая проблема может быть, что голос не выбран.

**Comment by abitrolly** [comment]
Хотел порекомендовать питоновский модуль с https://pypi.python.org/pypi/RHVoice а потом сообразил, что он только для винды собран.

**Comment by AlekseiCherkes** [comment]
>> bash: RHVoice: команда не найдена
Суть в этом. Команда есть на PATH?

Best regards, Cherkes Aleksey.

14 января 2016 г., 0:47 пользователь Anatoli Babenia <
notifications@github.com> написал:

**Comment by foozzi** [comment]
> Первая проблема может быть, что голос не выбран.
Разве не автоопределение? Каким образом мне это сделать.
> Суть в этом. Команда есть на PATH?
Я так тоже подумал, но суть в том, что я не знаю к чему путь прописывать, как такового бинарника RHVoice нет нигде, есть RHVoice-client и RHVoice-test

**Comment by foozzi** [comment]
Таким образом:
```
cat test.txt  |RHVoice-client -s Elena -r 0 -v 0 -p 0 > test.wav
```
 выходит записать текст на русском в файл без проблем, а вот воспроизвести не выходит

**Comment by vantu5z** [comment]
Попробуй как сказано вот тут https://aur.archlinux.org/packages/rhvoice-git/
1. Запусти RHVoice-service
2. После этого:  echo "проверка связи"|RHVoice-client -s elena|aplay -q

Лично я пользуюсь speech-dispatcher. Как его настроить описано в wiki и вот здесь http://archlinux.org.ru/forum/topic/2499/?page=8

**Comment by abitrolly** [comment]
>> Первая проблема может быть, что голос не выбран.
> Разве не автоопределение? Каким образом мне это сделать.

Насколько я понял в RHVoice нет автоопределения - можно только один голос или пару выбрать (профиль). По умолчанию выбран профиль с одним голосом для инглиша. Но надо в конфиге на твоей системе смотреть.

**Comment by foozzi** [comment]
>>
Попробуй как сказано вот тут https://aur.archlinux.org/packages/rhvoice-git/
1. Запусти RHVoice-service
2. После этого: echo "проверка связи"|RHVoice-client -s elena|aplay -q

Все гуд, работает отлично!
