### ISSUE TITLE
Компиляция на debian 7

### ISSUE THREAD

**Issue by foozzi** [Olga-Yakovleva/RHVoice#26]
Скомпилировал последний релиз с gihub на debian 7, ошибок не возникло, после пытаюсь выполнить тест:
``
echo test|RHVoice-test
``
на что получаю 
``
-bash: RHVoice-test: command not found
``
С RHVoice-client тоже самое, на арче после компиляции все завелось (см. прошлый топик)

**Comment by abitrolly** [comment]
Посмотри дебианизированный форк на https://github.com/minsk-hackerspace/RHVoice/ - подробности здесь - https://github.com/minsk-hackerspace/RHVoice/commit/a204f03e0c81579c4fab50a6b0ee94d695432f03

**Comment by foozzi** [comment]
В общем после компиляции, со всеми зависимостями, идет в /usr/local/bin/ и там будет наш RHVoice-test и остальные файлы, еще желательно добавить юзера в группу аудио:
``
usermod -G audio {user-login}
``
