### ISSUE TITLE
Почему RHVoice-client ломится к x11?

### ISSUE THREAD

**Issue by foozzi** [Olga-Yakovleva/RHVoice#28]
по сабжу 

```
root@dev:/usr/local/bin# cat test.txt | RHVoice-client -s Elena > test222.wav
Dbus error: 'Command line `dbus-launch --autolaunch=cc9393db6a79badad51388b656a3ad11 --binary-syntax --close-stderr' exited with non-zero exit status 1: Autolaunch error: X11 initialization failed.\n'
```

**Comment by foozzi** [comment]
решается таким образом:
```
export $(dbus-launch)
```

**Comment by abitrolly** [comment]
А всё-таки - почему?

**Comment by abitrolly** [comment]
#31 - дубликат.

**Comment by foozzi** [comment]
@abitrolly я думаю все же нужна сессия запущенного dbus, почему? как я понял из исходников, rhvoice нужны dbus нотифы (опять же, как я это понял)

**Comment by abitrolly** [comment]
Как я понял клиент с сервисом через эту шину общается. Вот коммит от Ольги, который выключает вообще его сборку - cfb6c2f673cfbb5
