### ISSUE TITLE
 RHVoice-client Dbus error

### ISSUE THREAD

**Issue by il-ya** [Olga-Yakovleva/RHVoice#31]
Машина Debian Linux,  без Иксов. При запуске  RHVoice-client выдает следующую ошибку:
echo "тест" | /usr/local/bin/RHVoice-client -s Irina -v 1 -r 1 -p 1 > test.wav
Dbus error: 'Command line `dbus-launch --autolaunch=gg19e47dd6f51b51f535c2cc5354b211 --binary-syntax --close-stderr' exited with non-zero exit status 1: Autolaunch error: X11 initialization failed.\n'

Можно это как-то побороть без установки иксов?

**Comment by abitrolly** [comment]
Чтобы ответить на этот вопрос надо понять зачем он `dbus-launch` запускает, а в исходниках что-то такой строки нет.

**Comment by abitrolly** [comment]
В общем анализ такой - `RHVoice` устанавливается в систему как `DBus` сервис, соответственно `RHVoice-client` - это клиент к нему, а не к библиотеке. Я так понимаю это сделано для читалок, чтобы они могли найти RHVoice через шину и взаимодействать с ним. Можно патчить клиента, чтобы он юзал либу напрямую.

`DBus` почему-то требует X11 сессию. Проблема описана здесь - http://unix.stackexchange.com/questions/105964/launch-a-fake-minimal-x-session-for-pulseaudio-dbus - решение поставить Xvfb - тоже иксы, только лёгкие, для рендера в память.

**Comment by foozzi** [comment]
@abitrolly я автору топика это в ВК описывал и на лоре в топике

**Comment by abitrolly** [comment]
@foozzi это можно во wrapper скрипт для клиента превратить? Я не смог запустить этого клиента в своё время, поэтму пользовался питоновским.

**Comment by Arhzi** [comment]
Взять DBus и сконфигурировать с флагом --disabled-x

**Comment by xor2003** [comment]
[discover_session_bus_address.sh.zip](https://github.com/Olga-Yakovleva/RHVoice/files/1929887/discover_session_bus_address.sh.zip)
