### ISSUE TITLE
невозможна компиляция рхвоиса на вижуал 2015.

### ISSUE THREAD

**Issue by zstanecic** [Olga-Yakovleva/RHVoice#32]
добрый вечерь! Я хотел компилировать тестовую под виндовс и я использоваль самый файл по умолчанию. сцонструцт который лежит в  исходнике. Как можно сделать чтоб он работал? он по умолчанию требует вс 2013 и этого вс нет. что надо изменить?

**Comment by abitrolly** [comment]
Давай полный лог того, что выдаёт при компиляции на экран.

**Comment by abitrolly** [comment]
И версию SCons тоже.

**Comment by zstanecic** [comment]
версиия сконса 2.4.1, пайтона 2.7.11
потому, что я использую нвда из исходников.

W dniu 15.02.2016 o 19:45, Anatoli Babenia pisze:

**Comment by zstanecic** [comment]
у меня такая ошибка, при инсталированном вс 2015
scons: Reading SConscript files ...
Mkdir("build\windows")
Checking for Visual Studio 2013... (cached) no
Error: Visual Studio 2013 is not installed
Это оригинальный исходник
W dniu 15.02.2016 o 19:44, Anatoli Babenia pisze:

**Comment by abitrolly** [comment]
Ага, вижу. [SConstruct](https://github.com/Olga-Yakovleva/RHVoice/blob/cfb6c2f/SConstruct#L45-L54) от RHVoice сам детектит компилятор (что, в общем-то понятно и правильно, но сделано странно).

Насколько я помню, NVDA работает через Python, а модуль RHVoice под Python так устроен, что ему всё равно чем собрана .dll Так что чем сейчас искать как детектить MS VS 2015, попробуй собрать с MinGW.

**Comment by zstanecic** [comment]
а рхвоис можно компилироват с мингв?
я хочу его покомпилировать под вс 2015, если возможно.
потому что я следил все инструкции, на сайте, и я работал 2 ч над этым.
можно ли как модифицировать сконс? чтоб он заработал?

W dniu 15.02.2016 o 20:06, Anatoli Babenia pisze:

**Comment by abitrolly** [comment]
SCons умеет и с MinGW, и с VS 2015, но я смотрю всё равно надо модифицировать SConstruct, чтобы заработало. Так как у меня нет Visual Studio 2015, то конкретно под неё ничем помочь не могу. Хотя можешь поправить функцию `def CheckVS(context)` и поменять блок:

```
    try:
        with _winreg.OpenKey(_winreg.HKEY_LOCAL_MACHINE,r"SOFTWARE\Microsoft\VisualStudio\12.0\Setup\VC",_winreg.KEY_READ|_winreg.KEY_WOW64_32KEY) as key:
            context.env["VCDir"]=_winreg.QueryValueEx(key,"ProductDir")[0]
    except WindowsError:
        result=0
```
на
```
   context.env["VCDir"] = "путь к твоему Visual Studio"
````

Возможно VS 2013 была выбрана не случайно,а для обеспечения бинарной совместимости с другим софтом, кроме NVDA.

**Comment by zstanecic** [comment]
я сейчас попробовал с изменёными параметрами и есть такая ситуация
c:\github\RHVoice>scons
scons: Reading SConscript files ...
Mkdir("build\windows")
Checking for Visual Studio 2015... (cached) yes
Checking for Unicode NSIS... (cached) yes
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
CalledProcessError: Command '['cmd', '/e:on', '/v:on', '/c', 
u'C:\\Program Files (x86)\\Microsoft Visual Studio 
14.0\\VC\\vcvarsall.bat', 'x86', '&&', 'set']' returned
non-zero exit status 1:
   File "C:\github\RHVoice\SConstruct", line 289:
     build_for_windows(base_env)
   File "C:\github\RHVoice\SConstruct", line 262:
     build_binaries(base_env,"x86")
   File "C:\github\RHVoice\SConstruct", line 230:
     env=clone_base_env(base_env,arch)
   File "C:\github\RHVoice\SConstruct", line 177:
     env["ENV"]=get_msvc_env_vars(env,arch)
   File "C:\github\RHVoice\SConstruct", line 74:
output=subprocess.check_output(["cmd","/e:on","/v:on","/c",setenv_script,arch,"&&","set"])
   File "c:\Python27\lib\subprocess.py", line 573:
     raise CalledProcessError(retcode, cmd, output=output)

c

что сейчасн надо изменить?
W dniu 15.02.2016 o 20:23, Anatoli Babenia pisze:

**Comment by abitrolly** [comment]
Пробелы в пути мешают. Путь надо в доп.кавычках указать, или прописать его, как короткий путь, типа C:\Progra~1\...

**Comment by zstanecic** [comment]
Я перекомпилировал на
рхвоиса на 2013!
работает!

W dniu 15.02.2016 o 21:36, Anatoli Babenia pisze:

**Comment by Olga-Yakovleva** [comment]
Сейчас должно компилироваться как с Visual Studio 2015, так и с Visual 
Studio 2013. Протестируйте, пожалуйста.

Замечание на всякий случай, так как сама только что с этим столкнулась: 
по умолчанию не всё ставиться, нужно вручную отметить, чтобы всё, 
связанное с C++, установилось.

**Comment by zstanecic** [comment]
Добрый вечер, Олга яковлева!
сейчас попробую.
У меня тоже один вопрос, для которого я сделаю новый issue.
что нужно, для создания хорватского голоса и языка для рхвоис?
как можна компилироват голосы на 24 кгц с новым движком?
с уважением,
ЗС

W dniu 16.02.2016 o 17:17, Olga-Yakovleva pisze:

**Comment by zstanecic** [comment]
работает!
как можно компилировать версию для 24 кгц?


W dniu 16.02.2016 o 17:17, Olga-Yakovleva pisze:

**Comment by abitrolly** [comment]
> как можно компилировать версию для 24 кгц?

Это уже вопрос для другого тикета, а этот уже можно закрыть, если проблема решена.

**Comment by denis-itskovich** [comment]
У меня ошибка при запуске scons:

	scons: Reading SConscript files ...
	Mkdir("build\windows")
	Checking for Visual Studio ... (cached) yes
	Checking for Unicode NSIS... (cached) no
	Checking for NSIS... (cached) no
	Mkdir("build\windows\x86")
	Configuring the build system for x86
	Checking whether the C compiler works... yes
	Checking whether the C++ compiler works... yes
	Checking for pkg-config... yes
	Checking for libpulse-simple... yes
	Checking for ao... yes
	Checking for portaudio-2.0... yes
	AttributeError: 'SConsEnvironment' object has no attribute 'InstallProgram':
	  File "C:\dev\projects\RHVoice\SConstruct", line 288:
		build_for_windows(base_env)
	  File "C:\dev\projects\RHVoice\SConstruct", line 260:
		build_binaries(base_env,"x86")
	  File "C:\dev\projects\RHVoice\SConstruct", line 238:
		duplicate=0)
	  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Script\SConscript.py", line 604:
		return method(*args, **kw)
	  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Script\SConscript.py", line 541:
		return _SConscript(self.fs, *files, **subst_kw)
	  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Script\SConscript.py", line 250:
		exec _file_ in call_stack[-1].globals
	  File "C:\dev\projects\RHVoice\src\sd_module\SConscript", line 42:
		local_env.InstallProgram(module)

Пробовал верси Scons: **2.5.1**, а также **3.0.1**
Python 2.7.15
Visual Studio 2017

Буду благодарен за помощь

**Comment by beqabeqa473** [comment]
здравствуйте.

в scons 3 надо изменить print на функцию print()

странно почему у вас смешанные этапы win и linux

On 6/5/18, Denis Itskovich <notifications@github.com> wrote:
> У меня ошибка при запуске scons:
>
> 	scons: Reading SConscript files ...
> 	Mkdir("build\windows")
> 	Checking for Visual Studio ... (cached) yes
> 	Checking for Unicode NSIS... (cached) no
> 	Checking for NSIS... (cached) no
> 	Mkdir("build\windows\x86")
> 	Configuring the build system for x86
> 	Checking whether the C compiler works... yes
> 	Checking whether the C++ compiler works... yes
> 	Checking for pkg-config... yes
> 	Checking for libpulse-simple... yes
> 	Checking for ao... yes
> 	Checking for portaudio-2.0... yes
> 	AttributeError: 'SConsEnvironment' object has no attribute
> 'InstallProgram':
> 	  File "C:\dev\projects\RHVoice\SConstruct", line 288:
> 		build_for_windows(base_env)
> 	  File "C:\dev\projects\RHVoice\SConstruct", line 260:
> 		build_binaries(base_env,"x86")
> 	  File "C:\dev\projects\RHVoice\SConstruct", line 238:
> 		duplicate=0)
> 	  File
> "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Script\SConscript.py",
> line 604:
> 		return method(*args, **kw)
> 	  File
> "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Script\SConscript.py",
> line 541:
> 		return _SConscript(self.fs, *files, **subst_kw)
> 	  File
> "C:\Python27\Scripts\..\Lib\site-packages\scons-2.5.1\SCons\Script\SConscript.py",
> line 250:
> 		exec _file_ in call_stack[-1].globals
> 	  File "C:\dev\projects\RHVoice\src\sd_module\SConscript", line 42:
> 		local_env.InstallProgram(module)
>
> Пробовал верси Scons: **2.5.1**, а также **3.0.1**
> Python 2.7.15
> Visual Studio 2017
>
> Буду благодарен за помощь
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/32#issuecomment-394746016


-- 
with best regards beqa

**Comment by denis-itskovich** [comment]
я пробовал и scons 2.5.1, кроме того, не совсем понятно где нужно менять
print на print(). Кроме того, падает скрипт у меня на env.InstallProgram

**Comment by Olga-Yakovleva** [comment]
Попробуйте сейчас.

Никогда не пробовала собирать под Windows с аудио-библиотеками, поэтому 
эту проблему не заметила.

Собственно, наверное, под Windows можно вообще отключить компиляцию 
модуля для Speech Dispatcher, так как он там не нужен, но пока просто 
отключила установку.

Правда, несколько озадачивает, что у вас обнаруживается даже 
libpulse-simple.
