### ISSUE TITLE
Ошибка сборки на rasbian (dietPI)

### ISSUE THREAD

**Issue by dobofongit** [Olga-Yakovleva/RHVoice#35]
При сборке RHVoice под rasbian - вместо голоса - шипение.
Под dietpi (облегченный rasbian) - читает первые несколько слогов.
Компилируется все хорошо, ошибок нет scons check все библиотеки видит.

**Comment by abitrolly** [comment]
Голос и текст - английский? Запускаешь через `RHVoice-client` надо полагать? Мои следующие действия - попробовать через Python https://github.com/Olga-Yakovleva/RHVoice/pull/34 но ХЗ когда до него добраться получится.

**Comment by dobofongit** [comment]
голос и текст - русский. запускаю RHVoice-test
беру ссылку из  git://github.com/Olga-Yakovleva/RHVoice.git
там клиента нет. 
Или я что-то не так делаю?

**Comment by dobofongit** [comment]
Решение:
libpulse-simple.
ao
portaudio-2.0
помогла сборка из исходников
