### ISSUE TITLE
Win8: 0.5 версия не работает вообще, 0.4 не правильно работает со словарями.

### ISSUE THREAD

**Issue by SurikenTSD** [Olga-Yakovleva/RHVoice#36]
В общем, windows 8 x64, устанавливаю 0.5 версию - в sapi5 пропадают все движки, чистый белый список из одной строчки. Удаляю 0.5 версию - возвращается список с дефолтными движками.
Ставлю 0.4 версию - более или менее адекватно читает только со словарями RHVoice.rex и Sapi5_RHVoice_0.rex_3.dic. Но читает как-то стремно, плюс цифры всякие и некоторые вещи читает так, что вообще не понять. При подключении 1 и 2 словаря читает вообще невразумительно, вставляет в слова непонятные буквы. К примеру:

"Тоже склоняюсь к версии Алексея" читает как "Ткоже склоняюсь к версии Алекскея" и так далее.

Как решить проблему? Хотелось бы вообще 0.5 версию поставить, но сойдет и 0.4 с работающими словарями.

**Comment by SurikenTSD** [comment]
Я понял, в чем проблема, но не могу ее устранить. Символ ударения в словарях Q вместо того, чтобы играть свою роль, читается, отсюда и лишнее "к" в словах.

**Comment by SurikenTSD** [comment]
Вместо балаболки через демагога попробовал проверить, после установки 0.5 версии выдает ошибку "не найден речевой драйвер Microsoft SAPI5". Удаляю 0.5, ставлю 0.4 - драйвер сразу находится. Символ ударения в демагоге так же читается, как и в балаболке. Пытался при установленной 0.5 версии реанимировать драйвер, скачивал его с сайта майкрософт, устанавливал - не помогло.

**Comment by zstanecic** [comment]
У меня на десятке, всё корректно работает.
У меня есть версии 0.5.

W dniu 11.03.2016 o 10:24, SurikenTSD pisze:

**Comment by SurikenTSD** [comment]
Чистую 10ку поставил, установил - нифига. Опять чистый список.

**Comment by SurikenTSD** [comment]
Надо было установить Language pack

**Comment by SurikenTSD** [comment]
Вот только как читал символ ударения, так и читает...
"СтрКанно было оказаться вдруг одномКу" >_>

Вот как в словаре выглядит "ъъстрQанноъъ"

**Comment by alex19EP** [comment]
too old to be relevant i think. 🤔
