### ISSUE TITLE
Есть задача реализовать анимацию говорящей головы.

### ISSUE THREAD

**Issue by 6opb6a** [Olga-Yakovleva/RHVoice#37]
При использовании вашего синтезатора, есть ли такая возможность получить состояние сигнала на аудио-выходе. Для того, чтобы синхронизировать движение губ с воспроизводимой репликой.?

**Comment by linvinus** [comment]
непонятно что имеется ввиду под "состояние сигнала на аудио-выходе"
может просто  оцифровать аналоговый сигнал со звуковой карты? это любой контроллер может

**Comment by abitrolly** [comment]
@6opb6a есть возможность получить прям дискретизированный сэмпл, который можно хоть на выход, хоть в анализатор, хоть в Blender. Но писать код придётся. )

**Comment by abitrolly** [comment]
Но это плохой способ (я не про Blender). Круче сделать в Blender motion tracking реального видео с губами, привязать это к тексту, ввести в HMM модель эти переменные искажения кривизны, и научить сразу читать сурдоперевод для людей со слабым слухом. =) Т.е. не надо через ж (т.е. через звук) это прогонять, чтобы не терять сигнал.
