### ISSUE TITLE
RHVoice-service жрет память

### ISSUE THREAD

**Issue by il-ya** [Olga-Yakovleva/RHVoice#38]
Версия 0.5.1, запущенная под Linux.  При длительном использовании ясно видно, что RHVoice-service не освобождает память и раздувается, чем дальше, тем больше. Есть какие-нибудь пути решения этой проблемы?

**Comment by abitrolly** [comment]
Проверить тулзами с https://github.com/google/sanitizers/wiki/AddressSanitizerComparisonOfMemoryTools и запостить результат сюда. Инструменты типа DBI по идее даже не требуют пересборки.

**Comment by alex19EP** [comment]
ok RHVoice server got disabled long time ago.
