### ISSUE TITLE
онлайн демонстрация синтезатора.

### ISSUE THREAD

**Issue by beqabeqa473** [Olga-Yakovleva/RHVoice#40]
здравствуйте все.

недавно написал веб сервис, с помощью которого можно онлайн познакомится с синтезатором.

адрес сервиса http://rhvoice.cloudapp.net:3000

ольга, если можно внести эту информацию в readme

**Comment by CHERTS** [comment]
Что-то видок у этого сервиса полный швах, тег ["select"](http://htmlbook.ru/html/select) не осилили? А как выбрать другие голоса кроме Anna, что вводить? А что вводить в pitch и rate человек сам должен догадаться?

**Comment by beqabeqa473** [comment]
пока да, потом посмотрим

**Comment by beqabeqa473** [comment]
список с голосами сделан. можно выберать

**Comment by CHERTS** [comment]
> список с голосами сделан. можно выберать
что то не работает выбор, говорит одним голосом не важно, что я выбрал Anna, что Irina

**Comment by beqabeqa473** [comment]
все работает.
попробуйте после выбора другово голоса ввести другой текст.

**Comment by awsom82** [comment]
не работает, 403

**Comment by beqabeqa473** [comment]
извените, сейчас все должно работать.

**Comment by linvinus** [comment]
очень полезная вещь! 
Туда стоит добавить 
1) описание как можно расставлять ударения чтобы получить качественную речь
2) кнопочку скачать wav файл. 

при первом открытии можно сразу же сказать "Добро пожаловать на страницу тестирования голосового движка RHVoice, введите фразу в поле Текст и нажмите кнопку Отправить."

**Comment by abitrolly** [comment]
Мне для счастья надо только только удобный контрол для выбора голосов. А то сложно понять, что там кроме Анны ещё вводить можно.

Я так понимаю это всё на JavaScript сконвертировано и работает всё в браузере?

**Comment by beqabeqa473** [comment]
здравствуйте.

нет, серверная чать на node.js использует библиотеку librhvoice.so на сервере.

сделаю комбинированный список для выбора голосов.

**Comment by beqabeqa473** [comment]
поповоду конвертирования в javascript, даже незнаю.

я както читал об этом, но тут врятли можно достичь высокой скорости.

**Comment by abitrolly** [comment]
Конвертировать C++ в JavaScript возможно через Emscripted https://kripken.github.io/mloc_emscripten_talk/gindex.html#/2 но да, тормоза дорлжны быть неимоверные. =) Ничего, скоро WebAssembly обрелизиться - вот там будет чем заняться.

**Comment by beqabeqa473** [comment]
я ддумаю для таких целей, помоему достаточно рест с использованием нативной библиотеки.

**Comment by abitrolly** [comment]
Да, только следи за тем, чтобы сервак не взломали. Код на C++ всё-таки и на безопасность его никто не прогонял.

**Comment by beqabeqa473** [comment]
кстати надо будет статический анализ на rhvoice провести

**Comment by abitrolly** [comment]
Да, интересно было бы в отдельный тикет весь прогресс сложить в качестве примера для последователей. =)

**Comment by edgiru** [comment]
демо уже не робит ((

**Comment by beqabeqa473** [comment]
здравствуйте.

демонстрационная страничка синтезатора востановлена и находится по ссылке
https://ttsapi.gozaltech.org/

**Comment by tolix** [comment]
Здравствуйте, опять сломался...

**Comment by alex19EP** [comment]
all links not working. so will close for now.
thanks for contribution
