### ISSUE TITLE
После компиляции и установки отсутствует RHVoice-client

### ISSUE THREAD

**Issue by 1690147** [Olga-Yakovleva/RHVoice#41]
Компиляция и установка проводились на Fedora 23 i686 (а также на Fedora 23 x86_64, Kubuntu 16.04 x86_64 — во всех случаях результаты аналогичны). `RHVoice-test` работает, однако нужна именно `RHVoice-client`, чтобы выводить звук в файл: `cat text.txt | RHVoice-client -s Aleksandr > voice.wav` (если такое можно проделать с `RHVoice-test`, то, пожалуйста, подскажите как).
Лог компиляции и установки: https://da.gd/6pavC (там не показана `sudo ldconfig`, но она выполнялась).

**Comment by ilyacuc** [comment]
@1690147 `echo 'text' | RHVoice-test -o file.wav`
Так работает только для английского текста. Для русского нужно подавать как-то так: `<?xml version="1.0"?><speak><p><s xml:lang="ru"><voice>текст</voice></s></p></speak>`. и с флагом -s

**Comment by 1690147** [comment]
@ilyacuc спасибо за наводку. Почитал `RHVoice-test --help` (что нужно было сделать с самого начала, но лень победила :), там обнаружил флаг -i для подстановки файла с текстом. В итоге для вывода звука в файл команда будет выглядеть так (для русского текста тоже работает): `RHVoice-test -p Aleksandr -i text.txt -o voice.wav`.
