### ISSUE TITLE
Украинский языковой модуль Android

### ISSUE THREAD

**Issue by GFOXSH** [Olga-Yakovleva/RHVoice#44]
Желая помочь разработке собрал украинский языковой модуль для Android версии R. H. Voice:
https://github.com/GFOXSH/RHVoice/releases/tag/1.0

**Comment by burunduk** [comment]
Репозиторий уже не доступен. @GFOXSH карточку можете закрыть?

**Comment by velmyshanovnyi** [comment]
можна закрыть этот тикет...

**Comment by alex19EP** [comment]
К сожалению некому. @Olga-Yakovleva может вы?
