### ISSUE TITLE
RHVoice-client: command not found

### ISSUE THREAD

**Issue by Headmaster11** [Olga-Yakovleva/RHVoice#47]
Здравствуйте.

Проблема с RHVoice. Установил на Linux Ubuntu-14. Команда `echo test|RHVoice-test` выдаёт
`default Engine is default`

При запуске `RHVoice-test --help` все ок. Если запускаю `RHVoice-client --help`

`RHVoice-client: command not found`

**Comment by vantu5z** [comment]
Временно отключили сборку сервера и клиента
смотри коммит:  cfb6c2f673cfbb56e5e0d9b25c68c2e69d2c55ad
Если собираешь из исходников, просто раскомментируй эту строку.

**Comment by techtonik** [comment]
Нет ничего более постоянного, чем временное.. )

**Comment by kolexander** [comment]
Здравствуйте 
раскомментировал, перекомпилил, переустановил 
sudo scons --clean install
scons
sudo scons install

echo test|RHVoice-test
RHVoice-test: command not found

в /usr/local/bin вижу только 
RHVoice-make-hts-labels
RHVoice-transcribe-sentences

в /usr/local/lib
libRHVoice.so.2.0.0
libRHVoice_core.so.0.0.0

**Comment by miradnanali** [comment]
To build the dbus service and RHVoice-client with a current build environment, you can do as follows.

As written above, in SConstruct uncomment line 218, so change
`218         #has_giomm=conf.CheckPKG("giomm-2.4")`
to
`218         has_giomm=conf.CheckPKG("giomm-2.4")`

Then, in SConstruct in the root directory, change line 162
`162         env.AppendUnique(CXXFLAGS=["-std=c++03"])`
to read (adding the new line below):
`162         env.AppendUnique(CXXFLAGS=["-std=c++11"])`
`163         env.AppendUnique(CXXFLAGS=["-Wno-deprecated-declarations"]) `

Now build and install as usual, e.g. on Debian/Ubuntu you might do:

`scons -j8 prefix=/usr`
`sudo checkinstall scons prefix=/usr install`
