### ISSUE TITLE
Как в Linux подключить словари ударений для RHVoice?

### ISSUE THREAD

**Issue by simwin** [Olga-Yakovleva/RHVoice#49]
Добрый день! Подскажите, как в Linux можно подключить словари ударений для RHVoice, которые я нашёл здесь - http://golosknigi.com/page3.html (внутри файлы Sapi5_RHvoice_1.dic  Sapi5_RHvoice_3.dic Sapi5_RHvoice_0.rex  Sapi5_RHvoice_2.dic)

Есть ли возможность указывать прямо в тексте, что нужно сделать паузу, перед тем, как продолжить читать текст далее? 

Можно ли прямо в тексте указывать на замедление или ускорение чтения?

Я озвучиваю тексты следующим образом: cat 311.txt | RHVoice-test -p Anna

Есть ли другие способы? Зачем нужны программы RHVoice-make-hts-labels и RHVoice-transcribe-sentences

Спасибо за отличную программу и заранее благодарю за ответы!

**Comment by Voskrese** [comment]
@simwin здесь есть немного инфы
https://github.com/vantu5z/RHVoice-dictionary

пишу для тех кто так же хочет подключить, но инфы вовсе мало

**Comment by simwin** [comment]
Ольга, скажите, а какой формат словарей? Как правильно ставить ударение?
Через заглавную букву? И как правильно наименовать сам файл ударений?

2018-06-14 9:52 GMT+03:00 Voskrese <notifications@github.com>:

**Comment by Voskrese** [comment]
@simwin 
хмм... я не Ольга))

**Comment by simwin** [comment]
Ну, прошу прощения :). Ольги тоже пошёл вопрос )

2018-06-15 0:46 GMT+03:00 Voskrese <notifications@github.com>:

**Comment by vantu5z** [comment]
@simwin, @Voskrese хотел сказать, что по указанной им [ссылке](https://github.com/vantu5z/RHVoice-dictionary) есть примеры словарей, которые обновляются по мере возможности и желания, а также небольшое описание куда их класть (может отличаться в зависимости от дистрибутива Linux).
Ещё есть вот такой файлик в этом репозитории с примером словаря и описанием синтаксиса: [ссылка](https://github.com/Olga-Yakovleva/RHVoice/blob/master/config/dicts/Russian/example.txt).
Если планируете указывать ударение непосредственно в тексте, то необходимо указать в настойках каким символом это планируется делать (параметр `stress_marker`) [wiki](https://github.com/Olga-Yakovleva/RHVoice/wiki/Configuration-file-%28Russian%29).
По поводу пауз, ускорения/замедления - я про такие возможностей не знаю.

**Comment by simwin** [comment]
Иван, большое спасибо за подсказку!

15 июня 2018 г., 13:22 пользователь Ivan <notifications@github.com> написал:

**Comment by alex19EP** [comment]
Duplicate of #93

**Comment by Voskrese** [comment]
@alex19EP 
чем вы руководствовались при обнаружении повторных запросов? просто любопытно

![2020-06-17_182735](https://user-images.githubusercontent.com/10104740/84887542-77518380-b0c8-11ea-86fe-f9296c35c836.png)

![2020-06-17_182819](https://user-images.githubusercontent.com/10104740/84887549-791b4700-b0c8-11ea-97ec-ff625d9fc771.png)

и как вы заметили, здесь пишут в основном на русском, и большинство пользователи СЛАБОВИДЯЩИЕ, мало кто английский язык знает. почему отвечаете на английском?

**Comment by alex19EP** [comment]
mainly guided by intuition. and the amount of information in the ticket.

> большинство пользователи СЛАБОВИДЯЩИЕ, мало кто английский язык знает.

I sincerely hope that you do not think that the blind cannot know English.
disclaimer: I'm blind.

> и как вы заметили, здесь пишут в основном на русском

Unfortunately. I am sure that this limits the number of contributors.
would rather change that. RHVoice has long become an international speech synthesizer.

**Comment by Voskrese** [comment]
@alex19EP 
используя вашу логику, русские словари, надо писать на английском
вы уж будьте добры, если топик стартер и участники отписываются на своем родном и причем тема затрагивается именно русского языка в словаре или движка, объясняться на русском. надеюсь без обид и мы поняли друг друга
