### ISSUE TITLE
Отсутствует поддержка multijobs на стадии установки

### ISSUE THREAD

**Issue by msva** [Olga-Yakovleva/RHVoice#5]
Здравствуйте!
Я пытался написать ebuild для Gentoo и накнулся на тот факт, что билдскрипты построены таким образом, что -j со значением >1 вызывает ошибки в установке, связанные с тем, что установщик не может найти указанные файлы. Судя по всему, проблема в том, что он не сбрасывает текущий рабочий путь обратно в директорию с исходниками и из-за этого не может найти искомые файлы.
Если насильно указать "непередавание" scons'у -jN из MAKEOPTS'ов, то установка проходит успешно. Но Gentoo Developer handbook недвусмысленно намекает, что на подобные вещи нужно обязательно жаловаться в апстрим пакета и по возможности помогать исправить.
К несчастью, в scons я не знаток, так что не знаю, чем могу помочь. Но, тем не менее, заранее готов оказать любую помощь в устранении проблемы :)

**Comment by alex19EP** [comment]
i think issue is fixed long time ago. scons -j 8 works fine.

**Comment by msva** [comment]
yeah, it builds fine for now.

Although, there is still strange issue in that fact, that scons builds the code two times:
first time - on "compile" phase (where package manager calls `scons <...params...>`), and second time on install phase (where package manager calls `scons <...params...> install`). It supposed to just install already built binaries and libraries, when `install` is called, but somewhy, it reconfigures and rebuilds all the things again :(
Other than that - all the things works flawless!
Thanks a lot to Olga and all the contributors for their work!

**Comment by alex19EP** [comment]
> yeah, it builds fine for now.

I'm glad to hear that.

> Although, there is still strange issue in that fact, that scons builds the code two times:
first time - on "compile" phase (where package manager calls scons <...params...>), and second time on install phase (where package manager calls scons <...params...> install). It supposed to just install already built binaries and libraries, when install is called, but somewhy, it reconfigures and rebuilds all the things again :(
Other than that - all the things works flawless!

unfortunately I cannot confirm this. for me 
```
scons prefix="/usr" sysconfdir="/etc"
```
builds RHVoice. and 
```
scons install DESTDIR="${pkgdir}" prefix="/usr" sysconfdir="/etc"
```
just installs files.
can you provide logs? so I can investigate.
thanks.

**Comment by msva** [comment]
[rhvoice.build.log](https://github.com/Olga-Yakovleva/RHVoice/files/5541231/rhvoice.build.log)

// sorry for delay again

**Comment by msva** [comment]
(and even changing syntax to `scons install ....` doesn't help: it still rebuilds the app..

**Comment by msva** [comment]
uhm, interesting thing is that removing `-jN` from intall - helps...

looks like scons bug...

**Comment by msva** [comment]
Anyway, I "fixed" the issue by moving to the new CMake build system (although, it has few bugs too, but I already fixed them and will make a PRs)
