### ISSUE TITLE
Связь с разработчиками

### ISSUE THREAD

**Issue by uzhinskiy** [Olga-Yakovleva/RHVoice#52]
Добрый день.
Помогите связаться с разработчиками. У меня есть запрос на доработку кода за вознаграждение.
Спасибо.
Моя почта - lspci at mail.ru

**Comment by m-2k** [comment]
В чём проблема написать на почту разработчику?
Пожалуйста, не спрашивай как.

**Comment by foozzi** [comment]
о каком вознаграждении идет речь, если это open source проект, разработчики которые пишут код - делают это бесплатно

**Comment by decaprox** [comment]
@foozzi эм... похоже, вы очень мало знаете про open source разработку.

**Comment by lieff** [comment]
@m-2k Так почта вроде не указана?
@foozzi Не всегда, часто над open source работают и разработчики на зарплате.

**Comment by m-2k** [comment]
@lieff `/src/audio/audio.cpp:1`

**Comment by lieff** [comment]
@uzhinskiy ^^

**Comment by foozzi** [comment]
@decaprox  уж поверьте, за 8 лет достаточно
@lieff с инвестором - да, этот проект не относиться к данным

**Comment by alex19EP** [comment]
@Olga-Yakovleva profile now shows her email for github users so closing the issue.
