### ISSUE TITLE
English translation for "building on Linux"

### ISSUE THREAD

**Issue by alexarnaud** [Olga-Yakovleva/RHVoice#58]
Dear all,

I'm French, I help a blind friend who learn Russian to configure its GNU/Linux distribution to speak in Russian but I don't speak Russian myself.

Could it be possible to provide [these detailed instructions](https://github.com/Olga-Yakovleva/RHVoice/wiki/Building-on-Linux-%28Russian%29) in English ?

Best regards.

**Comment by Olga-Yakovleva** [comment]
I've published a rough translation. Translating my own convoluted 
sentences quickly is difficult even for me.

**Comment by alexarnaud** [comment]
It's perfect. Thanks a lot !

Best regards.
