### ISSUE TITLE
Проблема с лицензией

### ISSUE THREAD

**Issue by SunnyPage** [Olga-Yakovleva/RHVoice#68]
Нам очень нужна ваша помощь. Мы использовали вашу программу с Грузинским языком и нас обвенили в незаконном использовании базы для Грузинского языка. Предаставели нам патент. Обьясните пожалуйста кем создана Грузинская база. Как мы можем ее использовать.

**Comment by Olga-Yakovleva** [comment]
Запись базы организовало грузинское общество слепых. К сожалению, в 
процессе работы над проектом не были чётко сформулированы условия 
лицензии. Разрешается личное некоммерческое использование голоса, а 
использование в других целях нужно согласовывать с ними.

**Comment by SunnyPage** [comment]
Мы хотим создать свою базу. Какие инструменты для этого нам понадобятся. Не могли бы вы нам немного помочь.

**Comment by Olga-Yakovleva** [comment]
А речь идёт о новом голосе для вашего личного использования или он может 
быть включён в RHVoice?

**Comment by SunnyPage** [comment]
Да, может быть включен RHVoice. 

Можно пожалуйста узнать вашу личную почту. Моя почта gdaylight@gmail.com

**Comment by Olga-Yakovleva** [comment]
My email address should now be shown on my profile page, the question of the license was answered, and the question of creation of new voices is a separate topic, so closing.
