### ISSUE TITLE
Not clear how to make changes in language packs

### ISSUE THREAD

**Issue by denis-itskovich** [Olga-Yakovleva/RHVoice#69]
Hi

I'm trying to make some changes in **Tatar** language pack. I'm running build in windows environment. 
It's not clear for me how to make changes in language packs? It seems that when I make changes in `src/scripts/Tatar` folder, these changes do not have any impact on the produced language pack installer. I suspect that the language pack takes the binary files from `data/languages/Tatar`, but it's not clear how to produce these binary files from the source files. Should it be generated automatically when running `scons`? Or there is some special command line parameter for scons in order to generate them?

Thanks

---

Здравствуйте

Я пытаюсь сделать некоторые изменения в татарском языковом пакете. Мне не совсем понятно, что нужно запустить, чтобы сгенерировать бинарные файлы, находящиеся в `data/language/Tatar` из исходников в `src/scripts/Tatar`. Нужно ли использовать какой-нибудь особый аргумент для `scons`, чтобы сгенерировать эти файлы?

Заранее благодарен

**Comment by Olga-Yakovleva** [comment]
No, I never got around to integrating generation of those files into the 
compilation process.

I run Foma manually to compile them. I often make mistakes when I write 
those rules. Most of the time they are just errors in logic, which 
cannot be detected during compilation. First I test those rules in Foma 
by hand, checking if they output what I intend. As I always run Foma to 
experiment anyway, I never felt I really needed to automate the process.

  Then I save intermediate files. Usually it goes like this, if we don't 
include any manual testing:

foma -l <src_path>
write att <temp_path>
quit

Then I convert the rules into the binary format RHVoice understands:

./src/scripts/general/att2bin <temp_path> <bin_path>

**Comment by denis-itskovich** [comment]
Thanks, this worked!

**Comment by alex19EP** [comment]
if it works i will close
thanks
