### ISSUE TITLE
Как реализовать английский язык в RHVoice?

### ISSUE THREAD

**Issue by Yashalta** [Olga-Yakovleva/RHVoice#72]
Подскажите пожалуйста!
У меня сейчас стоит RHVoice на Debian 8 и все хорошо работает только по русски! Если ввоидить команды на английском то, RHVoice читает английский текст по русски! А так же цифры тоже произносит по русски!
Возможно в конфиге нужно, что то закоментировать и что то добавить для реализации английского?!?!
Или нужно установить библиотеку какую то!?!?!
HELP!

**Comment by Voskrese** [comment]
@Yashalta  странно, до гит добрался, а читать не хотим
https://github.com/Olga-Yakovleva/RHVoice/wiki/Configuration-file-%28Russian%29
