### ISSUE TITLE
Чз

### ISSUE THREAD

**Issue by c384mb** [Olga-Yakovleva/RHVoice#74]
Похоже, что для Чз  версия 0.7 не подходит (не поддерживается ?), Запустил установку, указал папку, установил и стандартная программа Речь в операционной системе перестала работать, запуская Речь получаю ошибку, в ней написано: "не могу найти,  что-то там dll, cpl", не запомнил. Пропали SAPi, их заменило, или удалило, или поломало. 

Воспользовался стандартным восстановлением. 

Если кому-то покажется, что Чз означает сокращение: что это за ерунда, нет это не так и тем более не с матом.

**Comment by Voskrese** [comment]
Все устанавливается, работает и ничего не ломается. Ищите проблемы у себя в системе

**Comment by Olga-Yakovleva** [comment]
Мне самой не на чем проверить, к сожалению. Если проблема действительно 
проявляется не на всех машинах с XP, то, возможно, зависит от того, 
какие обновления установлены. Согласно информации по Visual Studio, 
последние версии по умолчанию собирают программы, не совместимые с XP. 
Как сборка синтезатора организована сейчас, нет технической возможности 
попросить Visual Studio включить эту поддержку XP. Во всяком случае пока 
не удалось найти ответа на этот вопрос.

**Comment by Voskrese** [comment]
@Olga-Yakovleva  для ХР можно собрать отдельно, указав в toolset 140_xp или 141_xp

**Comment by Olga-Yakovleva** [comment]
Как я понимаю, toolset мы можем настроить только в проекте Visual 
Studio. Мы же не работаем с проектом. Сборка идёт с помощью SCons, 
который напрямую вызывает cl.exe, предварительно настроив переменные 
среды вызовом vcvarsall.bat. Не понятно, как поступать в таком случае. 
Возможно, такой способ и существует, но я не нашла информации о нём. 
Признаю, что я сама не сильна в сборке под Windows.

**Comment by beqabeqa473** [comment]
в scons 3 фprint стала функцией и каждый может завернуть ее в круглые скобки.
в остальном же изменений для rhvoice нет.

у меня собирается именно с scons 3

2018-07-08 12:23 GMT+04:00, zstanecic <notifications@github.com>:
> Привет ольга,
> Вы могли бы сделать изменение в sconsccruct, чтобы возможно было
> собирать синтезатор с сконсом 3?
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/74#issuecomment-403271506


-- 
with best regards beqa

**Comment by zstanecic** [comment]
в каком файле это нужно сделать?

**Comment by beqabeqa473** [comment]
конечноже в sconstruct

2018-07-08 16:18 GMT+04:00, zstanecic <notifications@github.com>:
> в каком файле это нужно сделать?
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/74#issuecomment-403283881


-- 
with best regards beqa

**Comment by c384mb** [comment]
Voskrese чютче надо к людям. А вы с высока птичьего полёта смотрите. Я не когда не собирал сам программы и не планирую собирать. Сложновато для моего понимания, но могу. 

То, что для Visual Studio надо указывать настройку для сборки, для XP я это тоже знал. Но знал как: один раз мне попалась в интернете такая информация. 

Из ходя из того, что я увидел: установка происходит нормально, после запуска Речь появляется предупреждение похожее на то, что появляется при запуске программ с отсутствующей поддержкой 2000/XP операционных систем. А поскольку я был уверен в это на 99% решил, что вы тут собираете сами программу и наверно лучше меня знаете и догадаетесь, что  собрано без поддержки XP.  

И это не самое главное. Самый главный посыл от меня. Ваша программа удаляет или заменяет  4 и 5 SAPI. По этому написать во время установки вашей программы: собрано без поддержки XP не устанавливать, ломается программа Речь, программа Речь больше работать не будет. И возле ссылки на скачивание это тоже упомянуть. Переустановка SAPI возможно поможет я не проверял, я воспользовался  программой Восстановлением системы входящая в состав XP.

**Comment by Voskrese** [comment]
@c384mb  откуда чуткость? я на экстрасенса не учился, и что такое Чз без матов так же не понял

> хотите услышать правильный ответ, задайте правильный вопрос, об этом даже дети знают

собирает программу сама Ольга, но и вы можете собрать ее из предоставленных исходных текстов под себя, поправьте то что нужно и скомпилируйте

на счет поддержки ХР в версии 0.7, видимо надо указать что нет ее
используйте версию 0.5

**Comment by c384mb** [comment]
Чз - это загадка и если есть русско-английская клавиатура решается просто, смотрим на клавиатуру и понимаем, что это значит, а поскольку XP уже упоминается то и ответ уже есть. Если кому-то покажется, что Чз ( сокращение ) означает сокращение: Что это За ерунда ( X... ), нет это не так и тем более не с матом. 

Чютче это я имел ввиду не перед фактом ставить, что у вас программа работает, а задать хотя бы несколько вопросов для прояснения почему у меня не работает если той информации, что я дал выше не хватает. 

Ваша программа, что делает с SAPI 4 и 5 удаляет или заменяет или ...?

Скомпилировать не мало программ можно если исходный материал для компиляции доступен, но дело в том насколько это надо людям, чтобы научится компилировать программу или программы. Пока мне это не нужно.

**Comment by Olga-Yakovleva** [comment]
RHVoice в SAPI5 добавляет только дополнительные ключи в реестр для 
регистрации голосов - ничего не заменяет и не удаляет. Но при удалении 
из системы сама библиотека синтезатора должна вызываться для удаления 
ключей. Поэтому, возможно, если SAPI5 автоматически пытается загрузить 
все зарегистрированные синтезаторы, а библиотека даёт сбой, будут 
проблемы, которые можно только ручным удалением ключей RHVoice из 
реестра решить.

У меня есть идеи, как можно попробовать модифицировать сборку, чтобы 
обеспечить совместимость с XP. Но, как я говорила, мне самой такую 
версию протестировать негде, чтобы узнать эффект этих правок.

**Comment by c384mb** [comment]
Вы для себя оцените и чётко решите будете дальше поддерживать XP или нет. А пока напишите возле ссылке на скачивание 0.7 версии, что не совместимо с XP. 
Пока я пользуюсь XP и в ближайшее время (речь о годах) не планирую переходить на 10 из-за отсутствия денег на покупку 10 и могу проверить для себя как будет работать 0.7 версия. Да и надо посмотреть 0.5. Я как и вы могу это проверить в виртуальной машине с установленной XP так проще и безопаснее.

**Comment by c384mb** [comment]
Если ваша программа каким-то образом будет и в дальнейшем нарушать работу  SAPI 4 и 5, то мне придётся от неё отказаться и не факт, что она вообще мне нужна. Один раз установил, что бы посмотреть и получил, то, что описал выше.

**Comment by Voskrese** [comment]
@c384mb ну это ваше сугубо личное дело

Только лишь подмечу, что этот рус. речевой движок, лучший среди бесплатных :wink:

На счет ХР, разработчик вас услышал, ответ выше, ждите и видимо исправления в будущем будут

**Comment by zstanecic** [comment]
Конечно, я согласен с коллегой, который сказал, что выше-упомянутый 
синтезатор - самый лучший русский синтезатор речи.
Ещё должен добавить, что хорошо с ним ловить орфографические ошибки.
с уважением,
Звонимир

**Comment by beqabeqa473** [comment]
да хватит уже ныть.
вопервых работу других компонентов он не нарушает.
вы сами в себе разберитесь.
к sapi4 rhvoice вообще не имеет отношений, а в sapi 5 как было сказано
просто в реестр вписывается информация для регистрации голосов.



2018-07-09 21:53 GMT+04:00, zstanecic <notifications@github.com>:
> Конечно, я согласен с коллегой, который сказал, что выше-упомянутый
> синтезатор - самый лучший русский синтезатор речи.
> Ещё должен добавить, что хорошо с ним ловить орфографические ошибки.
> с уважением,
> Звонимир
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/74#issuecomment-403565078


-- 
with best regards beqa

**Comment by CHERTS** [comment]
@c384mb кто вас так учил неуважительно общаться, да еще и с наездами и претензиями?
Версия 0.5 на winxp работает без проблем, сам долгое время пользовался ей. Если у вас возникли проблемы, то не нужно наездов, просто обьясните суть проблемы и попросите помочь.
А если не дождались помощи или у разработчика нет возможности Вам помочь, то это опять же не повод качать права, уважайте разработчика (Ольгу) и других учасников сообщества.

**Comment by c384mb** [comment]
1. Не надо так эмоционально. Вы меня не поняли. Может не выспались или ещё что помешало.
2. И ещё немого для понимания напишу. Не каких претензий я не предъявлял и помощи не просил и не прошу, я только описал как прошла первая и единственная установка 0.7 версии у меня на XP. И посоветовал предупредить об этом людей. Предупредить это будет правильно. А пока программа отдаётся с этого сайта без  предупреждения о последствиях после установки на XP. 
3. Предыдущими версиями этой программы я не пользовался и не устанавливал. На основе прочитанного выше предположил и предложил проверить работу 0.5 версии на XP, а вдруг вы и 0.5 версию не проверяли как работает на XP.
4. Даю видео в подтверждении моих слов. Установку производил на XP в виртуальной машине. Единственное, что не повторилось это голос для 4 SAPI из программы не пропал. По чему теперь так не знаю, два раза проверял.
5. И не надо общаться на повышенных тонах это совет. А на оборот надо порадоваться, что я не поленился вам об этом сообщить и объяснить. 

https://ufile.io/qvget

Те кто усомнился в моих словах, запускали 0.7 версию на XP?

**Comment by c384mb** [comment]
Даты не правильные. Я создал первое ( тему ) сообщение примерно 4 или 5 дней назад. А не как не 16 дней назад как в теме указано. "opened this Issue 16 days ago" и следующее сообщение было сразу на следующий день или в тот же день, а не через 9 дней как числится. второе сообщение.

**Comment by c384mb** [comment]
Кто из написавших в теме обратил внимание когда было создана мной тема? Я помню, что около 5 - 7 дней назад. А написано, что тема создана 16 дней назад.

**Comment by beqabeqa473** [comment]
у вас видимо в добавок к наглостью, и не расборчивостью какая
программа что делает, еще и с памятью проблемы.
или вы уже незнаете за что зацепится.
очень людям интересно когда вы открыли issue, или это имеет
существенный характер?

первое сообщение было 27-го июня, так вот перещитайте своим умом
сколько дней прошло.

2018-07-13 2:17 GMT+04:00, c384mb <notifications@github.com>:
> Кто из написавших в теме обратил внимание когда было создана мной тема? Я
> помню, что около 5 - 7 дней назад. А написано, что тема создана 16 дней
> назад.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Olga-Yakovleva/RHVoice/issues/74#issuecomment-404668125


-- 
with best regards beqa

**Comment by c384mb** [comment]
Я не подписываюсь на почту, чтобы получать уведомления о новых сообщениях не где и некогда если это не новостная рассылка. Мне так не удобно. Я пользуюсь закладками в браузере. Да получается я забыл когда создал свою тему. По этому и спросил в теме. 16 дней назад мне показалось слишком давно так как основанная дискуссия идёт гораздо позднее, а вдруг что-то с сайтом и дата отобразилась не верно или ещё что.  Обсуждение даты это мелочь, надеюсь это мы прояснили и проехали.

beqabeqa473 ну хорошо вы сами напросились хотите пообщаться по другому получите. 
Для Ольги. Я отслеживать как развивается программа не буду. Если вам Олга надо, чтобы я в ближайшее время проверил как будет работать ваша программа в XP давайте что-то другое для общения, не публичное, почта подойдёт. Если через меня вам по каким то причинам проверять не надо, тогда всё тема закрыта для меня. 

Не видя как работает этот голосовой движок на XP я не могу вам и себе ответить нужен он мне или не нужен. Я не видел в работе эту программу.

**Comment by Olga-Yakovleva** [comment]
Версия 0.7.1 должна быть теоретически совместима с XP SP3. Пока вопрос 
остаётся открытым до чьего-либо подтверждения или опровержения.

**Comment by alex19EP** [comment]
Windows XP is not supported for several years. so i close the ticket.

**Comment by alex19EP** [comment]
I also saw problems with a constructive dialogue among some participants, so I limit commenting on this issue if there is a constructive offer I propose to open a new one.
thank you for contribution.
