### ISSUE TITLE
RHVoice-test не делает output ((

### ISSUE THREAD

**Issue by kaneghost** [Olga-Yakovleva/RHVoice#77]
Здравствуйте Ольга!
не могу разобраться почему команда : echo "Привет!" | RHVoice-test -o "1.wav" -p anna
не приводит к тому чтобы появидся wav фаил с записью синтезированного слова Привет.
Пробовал на разных машинах с разным установленным дистрибутивом linux(Ubuntu, debian, kali)
Пробовал менять пути к output файлу(от корня). без кавычек, в одинарных ковычках, От рута, пробовал фаил через touch создавать.Вообщем никание танцы с бубном мне не помогли. Вся надежда на Вас.

**Comment by Olga-Yakovleva** [comment]
В текущей реализации запись в файл реализована вызовом libao. Одна из 
многочисленных вещей в синтезаторе, которые нужно добавить или 
исправить. А пока нужно собирать с libao.

Устанавливали ли вы libao и находит ли он её при сборке (смотреть на 
строчки вида "checking for...").

**Comment by kaneghost** [comment]
Спасибо! установил libao4 libao-dev. Пересобрал через scons --config=force. Установил. и все получилось. Еще раз благодарю!
