### ISSUE TITLE
Executables fail: Cannot open "build/freebsd/audio/libRHVoice_audio.so"

### ISSUE THREAD

**Issue by yurivict** [Olga-Yakovleva/RHVoice#81]
```
$ RHVoice-test
Cannot open "build/freebsd/audio/libRHVoice_audio.so"
```

Executables also appear to be linked to shared libraries in a wrong way:
```
$ ldd /usr/local/bin/RHVoice-transcribe-sentences
/usr/local/bin/RHVoice-transcribe-sentences:
	build/freebsd/core/libRHVoice_core.so (0)
	libc++.so.1 => /usr/lib/libc++.so.1 (0x800853000)
	libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x800b21000)
	libm.so.5 => /lib/libm.so.5 (0x800d40000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x800f6e000)
	libthr.so.3 => /lib/libthr.so.3 (0x80117d000)
	libc.so.7 => /lib/libc.so.7 (0x8013a5000)
```
The path ```build/freebsd/core/``` don't have to be there.
```libRHVoice_audio.so``` probably should be listed.

**Comment by Olga-Yakovleva** [comment]
I've made a couple changes. Please try to build the latest code.

**Comment by yurivict** [comment]
The build succeeds now.

But the README talks about the command line tool `rhvoice-client`, and no such program is installed.
Is it forgotten, or is README incorrect?

It installed these executables:
```
bin/RHVoice-make-hts-labels
bin/RHVoice-test
bin/RHVoice-transcribe-sentences
bin/sd_rhvoice
```

**Comment by alex19EP** [comment]
main problem fixed.
about rhvoice-client there is other issues for it.
