### ISSUE TITLE
Увеличение времени паузы между словами

### ISSUE THREAD

**Issue by ArtStack** [Olga-Yakovleva/RHVoice#87]
Здравствуйте!
Ольга, Спасибо за этот прекрасный программный продукт! Применяю его периодически уже более 2 лет, полезно, универсально, здорово!
Есть вопрос. Можно ли в текущей версии делать паузы между конкретными (помеченными в исходном тексте) словами? К примеру, если анализатор обнаруживает в тексте точку (или какой-либо другой непроизносимый спец. символ) то делает паузу бОльшую, чем обычно между словами. Если же нельзя, планируете ли Вы внести подобные изменения в продукт?

**Comment by alex19EP** [comment]
Duplicate of #97
lets continue discussion there.

**Comment by alex19EP** [comment]
Duplicate of #97
