### ISSUE TITLE
Add the Android version into F-Droid

### ISSUE THREAD

**Issue by KOLANICH** [Olga-Yakovleva/RHVoice#89]

**Comment by paulvi** [comment]
https://f-droid.org/

**Comment by ildar** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1255
@Olga-Yakovleva , Вы не против размещения программы в F-Droid?

**Comment by KOLANICH** [comment]
https://github.com/Olga-Yakovleva/RHVoice/blob/master/licenses/gpl-3.0.txt

**Comment by ildar** [comment]
Any volunteers to make the Fastlane file structure
<https://gitlab.com/snippets/1895688> ?
F-Droid guys ask that
<https://gitlab.com/fdroid/rfp/-/issues/1255#note_304549255>.

**Comment by ildar** [comment]
Подождём, может Ольга ответит. На следующей неделе продолжим с
мэйнтейнерами F-Droid.

**Comment by Olga-Yakovleva** [comment]
Is there anything only I can do to make this possible or can I leave
this to other people now that I have another person helping me to
maintain the project?

**Comment by alex19EP** [comment]
i think i can do it. a already started conversation with fdroid folks. need to create some files in the repo. I will do it soon.

**Comment by ildar** [comment]
Thanks a lot, we have it in F-Droid
