### ISSUE TITLE
Error: using 'typename' outside of template

### ISSUE THREAD

**Issue by ghost** [Olga-Yakovleva/RHVoice#9]
Приветствую
Пытаюсь собрать из исходников на CentOS получаю ошибку.
Код стянул через git clone.
Гуглил на эту тему. На буржуйских сайтах советуют пробовать запускать компиляцию под разные стандарты кода g++ -std=... Все стандарты перепробовал не помогает :)
## Need your help)
# cat /etc/system-release
## CentOS release 6.6 (Final)
# uname -a
## Linux cent0s.serv 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

---
# g++ -v

Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
## gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

[root@cent0s RHVoice]# scons
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler works... (cached) yes
Checking for pkg-config... (cached) yes
Checking for libpulse-simple... (cached) no
Checking for ao... (cached) yes
Checking for portaudio-2.0... (cached) no
Checking for giomm-2.4... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/linux/core/item.os -c -O2 -pthread -fPIC -DRHVOICE=1 -DPACKAGE=\"RHVoice\" -DVERSION=\"0.5.1\" -DDATA_PATH=\"/usr/local/share/RHVoice\" -DCONFIG_PATH=\"/usr/local/etc/RHVoice\" -Ibuild/linux/core -Isrc/core -Isrc/include -Isrc/third-party/utf8 -Isrc/third-party/tclap -Isrc/third-party/sonic -Isrc/third-party/rapidxml -Isrc/third-party/mage -Isrc/third-party/hts_engine src/core/item.cpp
In file included from src/include/core/config.hpp:22,
                 from src/include/core/params.hpp:19,
                 from src/include/core/language.hpp:23,
                 from src/core/item.cpp:24:
src/include/core/property.hpp: In member function 'virtual bool RHVoice::enum_string_property::check_value(const std::string&, std::string&) const':
src/include/core/property.hpp:288: error: using 'typename' outside of template
scons: **\* [build/linux/core/item.os] Error 1
scons: building terminated because of errors.

**Comment by alex19EP** [comment]
so i think it is fixed or OP updated to newer compiler. 😊
