### ISSUE TITLE
http://tiflo.info/rhvoice/ is outdated

### ISSUE THREAD

**Issue by paulvi** [Olga-Yakovleva/RHVoice#92]
http://tiflo.info/rhvoice/ site with information in Russian is outdated

**Comment by Menelion** [comment]
That page was authored by me a long time ago. Unfortunately, I have no access to it anymore, I'll request it again. I doubt though whether it's needed at all since everything is in the Wiki now.

**Comment by zstanecic** [comment]
А зачем тогда не удалить всё \это?

**Comment by alex19EP** [comment]
now it gives 404 so will close.

**Comment by abitrolly** [comment]
http://web.archive.org/web/20191107134940/http://tiflo.info:80/rhvoice/ just for the curious,

**Comment by alex19EP** [comment]
> 
> 
> http://web.archive.org/web/20191107134940/http://tiflo.info:80/rhvoice/ just for the curious,

ok 😀 good historical reference but not relevant any more.
